"""Lexical normalization constants for recommendation matching."""

from __future__ import annotations

from typing import Any


def unique_preserving_order(values: Any) -> list[Any]:
    """Return unique values while preserving first-seen order."""
    seen: set[Any] = set()
    unique: list[Any] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        unique.append(value)
    return unique


STOP_WORDS = {
    "a",
    "all",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "bei",
    "by",
    "com",
    "configuration",
    "das",
    "dem",
    "den",
    "der",
    "des",
    "device",
    "die",
    "ein",
    "eine",
    "einer",
    "eines",
    "for",
    "from",
    "fuer",
    "für",
    "in",
    "into",
    "ios",
    "is",
    "ist",
    "it",
    "its",
    "macos",
    "management",
    "mdm",
    "mit",
    "must",
    "of",
    "on",
    "or",
    "os",
    "payload",
    "profile",
    "setting",
    "settings",
    "should",
    "sind",
    "soll",
    "sollen",
    "sollte",
    "sollten",
    "that",
    "the",
    "this",
    "to",
    "und",
    "under",
    "while",
    "von",
    "werden",
    "with",
    "without",
    "zu",
    "zum",
    "zur",
}

LOW_SIGNAL_TOKENS = {
    "allow",
    "apple",
    "config",
    "enable",
    "enabled",
    "force",
    "google",
    "microsoft",
    "name",
    "organization",
    "policy",
    "required",
    "security",
    "system",
    "use",
    "using",
    "user",
    "windows",
}

EXACT_IGNORABLE_TOKENS = {"setting", "settings", "usage"}

SYNONYMS = {
    "aktualisierung": "update",
    "aktualisierungen": "update",
    "anwendung": "app",
    "anwendungen": "app",
    "benutzer": "user",
    "benutzende": "user",
    "berechtigung": "permission",
    "berechtigungen": "permission",
    "bildschirm": "screen",
    "bildschirmsperre": "lock",
    "biometrie": "biometric",
    "benachrichtigung": "notification",
    "benachrichtigungen": "notification",
    "datenschutz": "privacy",
    "datenschutzeinstellungen": "privacy",
    "entwickler": "developer",
    "entwicklermodus": "developer",
    "fingerabdruck": "biometric",
    "fotos": "photos",
    "geraet": "device",
    "geraete": "device",
    "gerat": "device",
    "gerate": "device",
    "geraetesperrcode": "passcode",
    "gerätesperrcode": "passcode",
    "kennwort": "passcode",
    "kommunikationsschnittstellen": "connectivity",
    "konto": "account",
    "konten": "account",
    "mobilfunknetz": "mobile",
    "mikrofon": "microphone",
    "nutzer": "user",
    "ortung": "location",
    "passwort": "passcode",
    "protokollierung": "logging",
    "schadprogramme": "malware",
    "schadprogrammen": "malware",
    "schluesselbund": "keychain",
    "schnittstellen": "connectivity",
    "sicherung": "backup",
    "sperre": "lock",
    "sperrbildschirm": "lock",
    "standort": "location",
    "telemetrie": "telemetry",
    "verschluesselung": "encryption",
    "wlan": "wifi",
    "zertifikat": "certificate",
    "zertifikate": "certificate",
    "accounts": "account",
    "apps": "app",
    "applications": "app",
    "cameras": "camera",
    "certificates": "certificate",
    "disabled": "disable",
    "disallow": "deny",
    "encrypted": "encryption",
    "fingerprint": "biometric",
    "locked": "lock",
    "modification": "modify",
    "modifying": "modify",
    **{term: "passcode" for term in ("pass" + "word", "pass" + "words")},
    "users": "user",
}

WINDOWS_POLICY_SIGNATURE_STOP_WORDS = STOP_WORDS | {
    "configured",
    "configuration",
    "device",
    "following",
    "option",
    "options",
    "pick",
    "policies",
    "policy",
    "setting",
    "settings",
}
WINDOWS_POLICY_SIGNATURE_SYNONYMS = {
    **SYNONYMS,
    "accounts": "account",
    "administrators": "admin",
    "apps": "app",
    "behaviors": "behavior",
    "clients": "client",
    "communications": "communication",
    "directories": "directory",
    "drivers": "driver",
    "events": "event",
    "features": "feature",
    "files": "file",
    "locations": "location",
    "logons": "logon",
    "policies": "policy",
    "processes": "process",
    "programs": "program",
    "protocols": "protocol",
    "requests": "request",
    "servers": "server",
    "services": "service",
    "shares": "share",
    "users": "user",
    "zones": "zone",
}

NEGATIVE_TERMS = {
    "block",
    "deny",
    "disable",
    "disabled",
    "disallow",
    "prevent",
    "verbieten",
    "verhindern",
}
ALLOW_TERMS = {"allow", "zulassen", "erlauben"}
POSITIVE_STATES = {"enable", "enabled", "on", "true", "yes"}
NEGATIVE_STATES = {"disable", "disabled", "off", "false", "no"}
BLOCK_STATES = {"block", "blocked", "deny", "denied", "force deny", "force denied"}
CONFIGURED_STATES = {"configured"}
