"""Semantic concept rules for certificates, apps, and account controls."""

from .mapping_types_and_constants import (
    ANDROID_PLAY_STORE,
    APPLE_APPLICATION_ACCESS,
    SemanticConceptRule,
    semantic_target,
)


SEMANTIC_CONCEPT_RULES_PART_2_CORE: tuple[SemanticConceptRule, ...] = (
    SemanticConceptRule(
        "certificates",
        "Zertifikate und Schlüssel",
        "Certificates and keys",
        (
            "zertifikat",
            "zertifikate",
            "certificate",
            "certificates",
            "wurzelzertifikat",
            "root certificate",
            "schlüssel",
            "schluessel",
            "keychain",
            "scep",
            "trust",
        ),
        (
            semantic_target(
                ("WINDOWS",),
                "relution-native",
                "WINDOWS_CERTIFICATE",
                ("certificate", "certificateTemplateForIdentityCertificate", "store"),
                "Windows certificate payloads can distribute trust and identity material.",
            ),
            semantic_target(
                ("MACOS",),
                "apple-schema-profile",
                "profile:com.apple.security.root",
                ("PayloadContent",),
                "Apple certificate payloads can distribute trusted certificates.",
            ),
            semantic_target(
                ("MACOS",),
                "apple-schema-profile",
                "profile:com.apple.security.scep",
                ("URL", "Subject"),
                "Apple SCEP payloads can request managed certificates.",
            ),
            semantic_target(
                ("IOS",),
                "relution-native",
                "IOS_CERTIFICATE",
                ("identityCertificateInfo",),
                "iOS certificate payloads can distribute trust and identity material.",
            ),
            semantic_target(
                ("IOS",),
                "relution-native",
                "IOS_SCEP",
                ("url", "subject", "keysize"),
                "iOS SCEP payloads can request managed certificates.",
            ),
            semantic_target(
                ("ANDROID_ENTERPRISE", "ANDROID"),
                "relution-native",
                "ANDROID_ENTERPRISE_CERTIFICATE",
                ("certificate", "certificateTemplate", "certificateUsage"),
                "Android Enterprise certificate policy can distribute trust and identity material.",
            ),
        ),
        ("BER.7.10", "BER.7.14", "DEV.7.2"),
    ),
    SemanticConceptRule(
        "app_allowlist",
        "App-Allowlist und Ausführungskontrolle",
        "App allowlist and execution control",
        (
            "allowlist",
            "whitelist",
            "app-installation",
            "installation von apps",
            "app allow",
            "app block",
            "app control",
            "app installer",
            "ms-appinstaller",
            "active x",
            "activex",
            "vbscript",
            "scriptlets",
            "xaml",
            "mark of the web",
            "ausführungskontrolle",
            "ausfuehrungskontrolle",
            "skripte",
            "scripts",
            "powershell",
            "erlaubte programme",
        ),
        (
            semantic_target(
                ("WINDOWS",),
                "relution-native",
                "WINDOWS_APP_COMPLIANCE",
                ("requiredApps",),
                "Windows app compliance can require managed applications.",
            ),
            semantic_target(
                ("WINDOWS",),
                "relution-native",
                "WINDOWS_APP_CONTROL",
                ("appControlId", "fileBaseInfo"),
                "Windows App Control is relevant to execution-control requirements.",
            ),
            semantic_target(
                ("WINDOWS",),
                "relution-native",
                "WINDOWS_CUSTOM_CSP",
                ("installSyncML",),
                (
                    "Relution Windows CSP evidence includes PowerShell and application-control "
                    "policy nodes."
                ),
            ),
            semantic_target(
                ("MACOS",),
                "relution-native",
                "MACOS_APP_COMPLIANCE",
                ("requiredApps",),
                "macOS app compliance can require managed applications.",
            ),
            semantic_target(
                ("MACOS",),
                "apple-schema-profile",
                "profile:com.apple.applicationaccess.new",
                ("familyControlsEnabled", "pathBlackList", "pathWhiteList"),
                "Apple application restrictions can represent app allow/deny decisions.",
            ),
            semantic_target(
                ("IOS",),
                "relution-native",
                "IOS_APP_COMPLIANCE",
                ("requiredApps", "whitelistedApps", "isBlacklist"),
                "iOS app compliance can require or restrict managed apps.",
            ),
            semantic_target(
                ("IOS",),
                "relution-native",
                "IOS_MANAGED_APP",
                ("bundleId", "content"),
                "iOS managed app configuration can scope app policy.",
            ),
            semantic_target(
                ("ANDROID_ENTERPRISE", "ANDROID"),
                "relution-native",
                ANDROID_PLAY_STORE,
                ("restrictedPlayStoreMode", "appAutoUpdatePolicy"),
                "Managed Play can restrict app availability and update policy.",
            ),
            semantic_target(
                ("ANDROID_ENTERPRISE", "ANDROID"),
                "relution-native",
                "ANDROID_ENTERPRISE_APP_POLICY",
                ("applications",),
                "Android Enterprise app policy can configure managed application scope.",
            ),
        ),
        ("KONF.6.1", "KONF.6.4", "BER.5.1"),
    ),
    SemanticConceptRule(
        "permissions_privacy",
        "Berechtigungen und Datenschutz",
        "Permissions and privacy",
        (
            "berechtigung",
            "berechtigungen",
            "permission",
            "permissions",
            "datenschutz",
            "privacy",
            "privileg",
            "zugriffsrecht",
            "zugriffsrechte",
            "tcc",
        ),
        (
            semantic_target(
                ("WINDOWS",),
                "relution-native",
                "WINDOWS_RESTRICTION",
                ("allowPrivacy", "allowPrivacyExperience", "allowSyncMySettings"),
                "Windows restrictions expose privacy-related toggles.",
            ),
            semantic_target(
                ("WINDOWS",),
                "relution-native",
                "WINDOWS_LOCAL_DEVICE_SECURITY",
                ("allowLocalAdminAccounts", "allowGuestAccounts"),
                "Windows local security policy can restrict local account privileges.",
            ),
            semantic_target(
                ("MACOS",),
                "apple-mobileconfig",
                "com.apple.TCC.configuration-profile-policy",
                ("service", "authorization"),
                "Apple PPPC profiles can govern macOS privacy permissions.",
            ),
            semantic_target(
                ("MACOS",),
                "relution-native",
                "MACOS_RESTRICTION",
                ("allowCamera", "allowCloudDocumentSync"),
                "macOS restrictions expose privacy-relevant toggles.",
            ),
            semantic_target(
                ("IOS",),
                "relution-native",
                "IOS_RESTRICTION",
                (
                    "allowCloudPrivateRelay",
                    "allowFindMyFriendsModification",
                    "allowCamera",
                ),
                "iOS restrictions expose privacy-relevant toggles.",
            ),
            semantic_target(
                ("ANDROID_ENTERPRISE", "ANDROID"),
                "relution-native",
                "ANDROID_ENTERPRISE_PERMISSION_MANAGEMENT",
                (
                    "defaultPermissionPolicy",
                    "wellKnownPermissions",
                    "customPermissions",
                ),
                "Android Enterprise permission policy can manage app permissions.",
            ),
        ),
        ("KONF.6.1", "KONF.6.4", "BER.5.1"),
    ),
    SemanticConceptRule(
        "cloud_sync",
        "Cloud- und Synchronisationsfunktionen",
        "Cloud and sync functions",
        (
            "cloud",
            "icloud",
            "online-funktionen",
            "online funktionen",
            "synchronisation",
            "synchronisierung",
            "sync",
            "handoff",
            "continuity",
            "onedrive",
            "microsoft cloud",
        ),
        (
            semantic_target(
                ("WINDOWS",),
                "relution-native",
                "WINDOWS_RESTRICTION",
                (
                    "allowSyncMySettings",
                    "allowAddingForeignAccountsManually",
                    "allowAccounts",
                ),
                "Windows restrictions can reduce Microsoft account and sync surfaces.",
            ),
            semantic_target(
                ("WINDOWS",),
                "relution-native",
                "WINDOWS_CUSTOM_CSP",
                ("installSyncML",),
                "Relution Windows CSP evidence includes Microsoft cloud and sync-related policies.",
            ),
            semantic_target(
                ("MACOS",),
                "relution-native",
                "MACOS_RESTRICTION",
                (
                    "allowCloudDocumentSync",
                    "allowCloudKeychainSync",
                    "allowCloudPhotoLibrary",
                ),
                "macOS restrictions can disable iCloud sync surfaces.",
            ),
            semantic_target(
                ("MACOS",),
                "apple-schema-profile",
                APPLE_APPLICATION_ACCESS,
                (
                    "allowCloudDocumentSync",
                    "allowCloudPhotoLibrary",
                    "allowCloudDesktopAndDocuments",
                ),
                "Apple restrictions schema covers iCloud sync controls.",
            ),
            semantic_target(
                ("IOS",),
                "relution-native",
                "IOS_RESTRICTION",
                (
                    "allowCloudBackup",
                    "allowCloudDocumentSync",
                    "allowCloudKeychainSync",
                    "allowCloudPhotoLibrary",
                ),
                "iOS restrictions can disable iCloud sync surfaces.",
            ),
            semantic_target(
                ("IOS", "MACOS"),
                "apple-schema-profile",
                APPLE_APPLICATION_ACCESS,
                ("allowCloudPhotoLibrary", "allowActivityContinuation"),
                "Apple restrictions schema covers iCloud and Continuity controls.",
            ),
            semantic_target(
                ("ANDROID_ENTERPRISE", "ANDROID"),
                "relution-native",
                "ANDROID_ENTERPRISE_PERSONAL_USAGE",
                ("accountTypesWithManagementDisabled", "personalPlayStoreMode"),
                (
                    "Android Enterprise personal-usage controls can reduce personal cloud account "
                    "surfaces."
                ),
            ),
        ),
        ("ASST.3.10", "KONF.11.8"),
    ),
    SemanticConceptRule(
        "telemetry",
        "Telemetrie und Diagnosedaten",
        "Telemetry and diagnostics",
        (
            "telemetrie",
            "telemetry",
            "diagnose",
            "diagnostic",
            "analytics",
            "connected user experience",
            "cuet",
            "usage data",
            "feedback notifications",
            "online tips",
            "search highlights",
            "news and interests",
            "suggested apps",
            "consumer experiences",
            "personalized recommendations",
        ),
        (
            semantic_target(
                ("WINDOWS",),
                "relution-native",
                "WINDOWS_RESTRICTION",
                ("allowPrivacy", "allowPrivacyExperience"),
                "Windows restrictions expose privacy and telemetry-adjacent controls.",
            ),
            semantic_target(
                ("WINDOWS",),
                "relution-native",
                "WINDOWS_CUSTOM_CSP",
                ("installSyncML",),
                "Relution Windows CSP evidence includes telemetry and diagnostic policy nodes.",
            ),
            semantic_target(
                ("MACOS", "IOS"),
                "apple-schema-profile",
                APPLE_APPLICATION_ACCESS,
                ("allowDiagnosticSubmission",),
                "Apple restrictions schema covers diagnostic submission.",
            ),
            semantic_target(
                ("MACOS",),
                "relution-native",
                "MACOS_RESTRICTION",
                ("allowAppleIntelligenceReport",),
                "macOS restrictions expose diagnostic and report-related toggles.",
            ),
            semantic_target(
                ("IOS",),
                "relution-native",
                "IOS_RESTRICTION",
                ("allowAppleIntelligenceReport",),
                "iOS restrictions expose diagnostic and report-related toggles.",
            ),
        ),
        ("DET.3.4", "DET.4.4"),
    ),
)
