"""Shared imports and immutable inputs for recommendation mapping modules."""

import re
from collections.abc import Callable
from pathlib import Path
from typing import Any
from .mapping_types_and_constants import (
    APPLE_ANALOG_RULES,
    APPLE_MOBILECONFIG_CANDIDATE_RULES,
    APPLE_MOBILECONFIG_EVIDENCE_PATH,
    APPLE_PASSCODE,
    APPLE_SCHEMA_CATALOG_PATH,
    APPLE_SCREEN_SAVER,
    AndroidAnalogRule,
    AppleAnalogRule,
    BSI_CONCEPT_MATCH_REASON,
    DIRECT_SEMANTIC_SOURCES,
    FieldEntry,
    GS_PLUSPLUS_SEMANTIC_SOURCES,
    MANAGEMENT_SUPPORT_CONCEPT_IDS,
    PROCESS_ONLY_TITLE_TERMS,
    RELATED_SEMANTIC_SOURCES,
    SemanticConceptRule,
    TEMPLATE_BUNDLE_PATH,
)
from ._android_analog_rules import ANDROID_ANALOG_RULES, ANDROID_CANDIDATE_RULES
from .semantic_concept_rules import SEMANTIC_CONCEPT_RULES
from .field_matching import (
    apple_schema_mapping,
    merge_apple_schema_mappings,
    relution_fields,
    apple_schema_fields,
    candidate_from_score,
    candidate_key,
    boolean_value_for_field,
    extract_setting_state,
    first_int,
    flatten_value_paths,
    flatten_leaf_items,
    is_exact_label_match,
    kind_priority,
    matched_rule_terms,
    normalize_search_text,
    phrase_groups_match,
    read_json,
    score_fields,
    stable_match_value,
    tokenize,
    unique_preserving_order,
    value_at_path,
    values_from_pairs,
)

__all__ = [
    'ANDROID_ANALOG_RULES',
    'ANDROID_CANDIDATE_RULES',
    'APPLE_ANALOG_RULES',
    'APPLE_MOBILECONFIG_CANDIDATE_RULES',
    'APPLE_MOBILECONFIG_EVIDENCE_PATH',
    'APPLE_PASSCODE',
    'APPLE_SCHEMA_CATALOG_PATH',
    'APPLE_SCREEN_SAVER',
    'AndroidAnalogRule',
    'Any',
    'AppleAnalogRule',
    'BSI_CONCEPT_MATCH_REASON',
    'Callable',
    'DIRECT_SEMANTIC_SOURCES',
    'FieldEntry',
    'GS_PLUSPLUS_SEMANTIC_SOURCES',
    'MANAGEMENT_SUPPORT_CONCEPT_IDS',
    'PROCESS_ONLY_TITLE_TERMS',
    'Path',
    'RELATED_SEMANTIC_SOURCES',
    'SEMANTIC_CONCEPT_RULES',
    'SemanticConceptRule',
    'TEMPLATE_BUNDLE_PATH',
    'apple_schema_fields',
    'apple_schema_mapping',
    'boolean_value_for_field',
    'candidate_from_score',
    'candidate_key',
    'extract_setting_state',
    'first_int',
    'flatten_leaf_items',
    'flatten_value_paths',
    'is_exact_label_match',
    'kind_priority',
    'matched_rule_terms',
    'merge_apple_schema_mappings',
    'normalize_search_text',
    'phrase_groups_match',
    're',
    'read_json',
    'relution_fields',
    'score_fields',
    'stable_match_value',
    'tokenize',
    'unique_preserving_order',
    'value_at_path',
    'values_from_pairs'
]
