

SEMANTIC_CONCEPT_RULES: tuple[SemanticConceptRule, ...] = (
    SemanticConceptRule(
        "passcode_authentication",
        "Authentisierung und Passcode",
        "Authentication and passcode",
        (
            "authentisierung",
            "anmeldung",
            "passwort",
            "kennwort",
            "passcode",
            "geraetecode",
            "gerätecode",
            "bildschirmsperre",
            "screen lock",
            "device lock",
            "password",
        ),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_PASSCODE", ("minLength", "quality", "history", "maxInactivityTime"), "Windows passcode policy can enforce concrete local sign-in values."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_HELLO", ("minimumPinLength", "allowBiometricAuthentication", "useTpm"), "Windows Hello covers PIN, biometric, and TPM-backed sign-in controls."),
            semantic_target(("MACOS",), "relution-native", "MACOS_SCREENSAVER", ("askForPassword", "askForPasswordDelay", "loginWindowIdleTime"), "macOS screen saver policy can require re-authentication after idle."),
            semantic_target(("IOS",), "relution-native", "IOS_PASSCODE", ("forcePIN", "minLength", "maxInactivityMinutes", "maxFailedAttempts"), "iOS passcode policy can enforce concrete device-code values."),
            semantic_target(("IOS", "MACOS"), "apple-schema-profile", APPLE_PASSCODE, ("minLength", "maxInactivity", "maxFailedAttempts"), "Apple passcode schema covers passcode and auto-lock constraints."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_DEVICE_PASSCODE", ("quality", "minLength", "maxFailedPasswordsForWipe"), "Android Enterprise passcode policy can enforce concrete device-code values."),
        ),
        ("BER.6.8", "BER.6.7", "BER.3.9", "BER.3.11"),
    ),
    SemanticConceptRule(
        "mfa",
        "Mehr-Faktor-Authentisierung",
        "Multi-factor authentication",
        ("mehr-faktor", "mehr faktor", "mfa", "multi factor", "two-factor", "2fa", "chipkarte", "smart card", "token"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_HELLO", ("useTpm", "allowBiometricAuthentication", "certificateForOnPremiseResources"), "Windows Hello can participate in stronger local authentication."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CERTIFICATE", ("certificate", "certificateTemplateForIdentityCertificate"), "Windows certificate payloads can support certificate-backed authentication."),
            semantic_target(("MACOS",), "apple-mobileconfig", "com.apple.security.smartcard", ("enforceSmartCard", "allowSmartCard"), "Apple smart card payloads are relevant when the local policy requires smart cards."),
            semantic_target(("IOS", "MACOS"), "relution-native", "IOS_CERTIFICATE", ("identityCertificateInfo",), "Apple certificate distribution can support certificate-backed authentication."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_CERTIFICATE", ("certificate", "certificateTemplate", "certificateUsage"), "Android Enterprise certificates can support certificate-backed authentication."),
        ),
        ("BER.7.10", "BER.7.14"),
    ),
    SemanticConceptRule(
        "lock_idle",
        "Sperre und Inaktivität",
        "Lock and idle timeout",
        ("inaktivität", "inaktivitaet", "idle", "sperrbildschirm", "bildschirmsperre", "auto lock", "autolock", "timeout"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_LOCAL_DEVICE_SECURITY", ("inactivityTimeUntilScreenSaver", "userInformationOnLockScreenConfiguration"), "Windows local security policy covers lock-screen and idle behavior."),
            semantic_target(("MACOS",), "relution-native", "MACOS_SCREENSAVER", ("askForPassword", "askForPasswordDelay", "loginWindowIdleTime"), "macOS screen saver settings can enforce idle lock behavior."),
            semantic_target(("IOS",), "relution-native", "IOS_PASSCODE", ("maxInactivityMinutes", "maxGracePeriodMinutes"), "iOS passcode policy covers auto-lock and grace-period values."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_DISPLAY", ("screenTimeoutMode", "screenTimeout"), "Android Enterprise display policy covers concrete timeout values."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_KEYGUARD_FEATURE_MANAGEMENT", ("keyguardDisabledFeatures",), "Android Enterprise keyguard policy can restrict lock-screen surfaces."),
        ),
        ("BER.6.8", "BER.3.11"),
    ),
    SemanticConceptRule(
        "encryption",
        "Verschlüsselung",
        "Encryption",
        ("verschlüssel", "verschluessel", "encryption", "filevault", "bitlocker", "efs", "encrypting file system", "kryptografisch"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_BITLOCKER", ("encryptionTypeForOsDrives", "fixedDrivesEncryptionType", "removableDrivesEncryptionType"), "Windows BitLocker policy covers drive encryption values."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CUSTOM_CSP", ("installSyncML",), "Relution Windows CSP evidence includes BitLocker and encryption-related policy nodes."),
            semantic_target(("MACOS",), "relution-native", "MACOS_FILE_VAULT", ("fdeFileVault",), "macOS FileVault policy covers disk encryption enforcement."),
            semantic_target(("MACOS",), "apple-schema-profile", "profile:com.apple.MCX.FileVault2", ("Enable", "Defer"), "Apple FileVault schema can express FileVault deployment settings."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", ANDROID_ADVANCED_SECURITY, ("encryptionPolicy",), "Android Enterprise advanced security can require encryption."),
        ),
        ("KONF.3.2", "ASST.4.2"),
    ),
    SemanticConceptRule(
        "updates",
        "Updates und Patches",
        "Updates and patching",
        ("update", "updates", "autoupdate", "patch", "patches", "aktualisierung", "aktualisierungen", "softwareupdate"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_UPDATE", ("autoUpdateType", "deadlineForFeatureUpdates", "deadlineForQualityUpdates"), "Windows Update policy can enforce update behavior once local cadence is known."),
            semantic_target(("MACOS",), "relution-native", "MACOS_UPDATE", ("automaticCheckEnabled", "automaticDownload", "criticalUpdateInstall"), "macOS update policy can enforce update behavior once local cadence is known."),
            semantic_target(("MACOS",), "apple-schema-profile", APPLE_SOFTWARE_UPDATE, ("AutomaticCheckEnabled", "CriticalUpdateInstall"), "Apple Software Update schema covers update enforcement settings."),
            semantic_target(("IOS",), "relution-native", "IOS_UPDATE", ("updateMode", "updateDays", "updateTime", "targetOSVersionLimit"), "iOS update policy can manage update scheduling and target versions."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", ANDROID_SYSTEM_UPDATE, ("systemUpdateType", "startMinutes", "endMinutes", "freezePeriods"), "Android Enterprise system update policy covers cadence and maintenance windows."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", ANDROID_PLAY_STORE, ("appAutoUpdatePolicy",), "Managed Play settings can enforce app update behavior."),
        ),
        ("KONF.8.2", "DET.5.10"),
    ),
    SemanticConceptRule(
        "malware_protection",
        "Schutz vor Schadsoftware",
        "Malware protection",
        (
            "schadsoftware",
            "schadprogramme",
            "schadcode",
            "malware",
            "antivirus",
            "virenschutz",
            "defender",
            "smartscreen",
            "play protect",
            "script scanning",
            "reputation",
        ),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_ANTIVIRUS", ("signatureUpdateInterval", "allowArchiveScanning", "realTimeScanDirection"), "Windows Antivirus policy covers Microsoft Defender-related settings."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CUSTOM_CSP", ("installSyncML",), "Relution Windows CSP evidence includes Defender and SmartScreen policy nodes."),
            semantic_target(("MACOS",), "relution-native", "MACOS_SYSTEM_POLICY_CONTROL", ("allowIdentifiedDevelopers", "enableAssessment"), "macOS system policy controls are relevant to Gatekeeper-style protection."),
            semantic_target(("IOS",), "relution-native", "IOS_WEB_CONTENT_FILTER", ("filterType", "autoFilterEnabled"), "iOS web filtering is a candidate for reputation-based web protection."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", ANDROID_ADVANCED_SECURITY, ("googlePlayProtectVerifyApps",), "Android Enterprise can enforce Google Play Protect verification."),
        ),
        ("KONF.7.1", "KONF.7.2", "KONF.7.6", "KONF.7.9", "KONF.7.10"),
    ),
    SemanticConceptRule(
        "firewall",
        "Firewall und Paketfilter",
        "Firewall and packet filtering",
        ("firewall", "paketfilter", "netzkommunikation", "netzzugriff", "incoming", "inbound"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_FIREWALL", ("domainProfile.enableFirewall", "privateProfile.enableFirewall", "publicProfile.enableFirewall"), "Windows Firewall policy can enforce profile-level firewall settings."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CUSTOM_CSP", ("installSyncML",), "Relution Windows CSP evidence includes Firewall MdmStore policy nodes."),
            semantic_target(("MACOS",), "relution-native", "MACOS_FIREWALL", ("enableFirewall", "blockAllIncoming", "enableStealthMode"), "macOS native firewall policy covers built-in firewall settings."),
            semantic_target(("MACOS",), "apple-schema-profile", "profile:com.apple.security.firewall", ("EnableFirewall", "BlockAllIncoming", "EnableStealthMode"), "Apple firewall profile can enforce built-in firewall settings."),
            semantic_target(("IOS",), "relution-native", "IOS_WEB_CONTENT_FILTER", ("filterType", "autoFilterEnabled"), "iOS has no host firewall profile, but web/content filtering can be relevant to network restriction goals."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_RECOMMENDED_GLOBAL_PROXY", ("proxyType", "host", "port", "pacUri"), "Android Enterprise has no host firewall template here; proxy policy is a related candidate."),
        ),
        ("KONF.7.15",),
    ),
    SemanticConceptRule(
        "network_connectivity",
        "VPN, WLAN, Proxy und Konnektivität",
        "VPN, Wi-Fi, proxy, and connectivity",
        ("vpn", "wlan", "wi-fi", "wifi", "wireless", "proxy", "apn", "mobilfunk", "schnittstelle", "schnittstellen", "bluetooth", "nfc", "tethering", "rdp", "remote desktop", "fernzugriff", "dns", "mdns", "multicast dns", "llmnr", "netbios", "smb", "nfs", "printer sharing", "internet sharing"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_VPN", ("alwaysOn", "serverNames", "vpnType"), "Windows VPN policy can enforce VPN profile properties once local values are known."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_WIFI", ("ssid", "authenticationType", "encryptionType"), "Windows Wi-Fi policy can configure institution networks."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_NETWORK_PROXY", ("useProxyServer", "proxyServer", "proxyServerPort"), "Windows proxy policy can configure concrete proxy values."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_REMOTE_DESKTOP", ("allowToConnectRemotely",), "Windows Remote Desktop policy is relevant to RDP exposure decisions."),
            semantic_target(("MACOS",), "apple-schema-profile", "profile:com.apple.vpn.managed", ("VPNType", "VPNSubType", "OnDemandEnabled"), "Apple VPN profile can configure managed VPN."),
            semantic_target(("MACOS",), "apple-schema-profile", "profile:com.apple.wifi.managed", ("SSID_STR", "EncryptionType"), "Apple Wi-Fi profile can configure managed Wi-Fi."),
            semantic_target(("MACOS",), "relution-native", "MACOS_NETWORK_PROXY", ("proxies.httpEnable", "proxies.httpsEnable", "proxies.proxyAutoConfigURLString"), "macOS proxy policy can configure concrete proxy values."),
            semantic_target(("IOS",), "relution-native", "IOS_VPN", ("vpnOnDemand", "vpnType", "server"), "iOS VPN policy can enforce managed VPN profiles."),
            semantic_target(("IOS",), "relution-native", "IOS_WIFI", ("ssid", "encryptionType", "autoJoin"), "iOS Wi-Fi policy can configure institution networks."),
            semantic_target(("IOS",), "relution-native", "IOS_GLOBAL_HTTP_PROXY", ("proxyType", "proxyServer", "proxyServerPort", "proxyPacUrl"), "iOS global HTTP proxy can configure proxy enforcement."),
            semantic_target(("IOS",), "relution-native", "IOS_CELLULAR", ("attachAPN", "apns"), "iOS cellular payload can configure APN values."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_DEVICE_CONNECTIVITY", ("usbDataAccess", "configureWifi", "wifiDirectSettings", "tetheringSettings", "apnPolicy"), "Android Enterprise connectivity policy covers interfaces and APN values."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_ALWAYS_ON_VPN", ("lockdownEnabled", "alwaysOnVpnApp.packageName"), "Android Enterprise can enforce always-on VPN once the VPN app is known."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_WIFI_MANAGEMENT", ("ssid", "securityType", "passphrase"), "Android Enterprise Wi-Fi policy can configure institution networks."),
        ),
        ("ARCH.3.4", "ARCH.4.1", "ARCH.5.1", "ASST.4.1", "KONF.3.7", "KONF.11.8"),
    ),
    SemanticConceptRule(
        "dns_resolution",
        "DNS und Namensauflösung",
        "DNS and name resolution",
        ("dns", "dns-server", "dns server", "private dns", "dns proxy", "dns settings", "namensaufloesung", "namensauflösung", "mdns", "multicast dns", "llmnr", "netbios name", "name resolution", "multicast name resolution"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CUSTOM_CSP", ("installSyncML",), "Relution Windows CSP evidence can carry Windows DNS, LLMNR, mDNS, and name-resolution policy nodes."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_VPN", ("dnsSuffixes",), "Windows VPN settings can scope managed DNS suffixes when the recommendation concerns managed network profiles."),
            semantic_target(("IOS", "MACOS"), "relution-native", "APPLE_DNS_SETTINGS", ("dnsSettings.dnsProtocol", "dnsSettings.serverAddresses", "dnsSettings.serverName", "prohibitDisablement"), "Apple DNS Settings can configure managed encrypted or explicit DNS resolvers once local resolver values are known."),
            semantic_target(("IOS", "MACOS"), "relution-native", "IOS_DNS_PROXY", ("appBundleIdentifier", "providerBundleIdentifier", "providerConfiguration"), "Apple DNS Proxy payloads can route DNS through a managed provider, but the app identifiers are organization-specific."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_STRONG_SWAN_PROFILE", ("dnsServers",), "Android Enterprise VPN profiles can carry DNS server values for managed VPN contexts."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_DEVICE_CONNECTIVITY", ("configureWifi", "wifiDirectSettings"), "Android Enterprise connectivity settings can support DNS-related network architecture decisions only indirectly."),
        ),
        ("ARCH.3.4", "ARCH.4.1", "ARCH.5.1"),
    ),
    SemanticConceptRule(
        "certificates",
        "Zertifikate und Schlüssel",
        "Certificates and keys",
        ("zertifikat", "zertifikate", "certificate", "certificates", "wurzelzertifikat", "root certificate", "schlüssel", "schluessel", "keychain", "scep", "trust"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CERTIFICATE", ("certificate", "certificateTemplateForIdentityCertificate", "store"), "Windows certificate payloads can distribute trust and identity material."),
            semantic_target(("MACOS",), "apple-schema-profile", "profile:com.apple.security.root", ("PayloadContent",), "Apple certificate payloads can distribute trusted certificates."),
            semantic_target(("MACOS",), "apple-schema-profile", "profile:com.apple.security.scep", ("URL", "Subject"), "Apple SCEP payloads can request managed certificates."),
            semantic_target(("IOS",), "relution-native", "IOS_CERTIFICATE", ("identityCertificateInfo",), "iOS certificate payloads can distribute trust and identity material."),
            semantic_target(("IOS",), "relution-native", "IOS_SCEP", ("url", "subject", "keysize"), "iOS SCEP payloads can request managed certificates."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_CERTIFICATE", ("certificate", "certificateTemplate", "certificateUsage"), "Android Enterprise certificate policy can distribute trust and identity material."),
        ),
        ("BER.7.10", "BER.7.14", "DEV.7.2"),
    ),
    SemanticConceptRule(
        "app_allowlist",
        "App-Allowlist und Ausführungskontrolle",
        "App allowlist and execution control",
        ("allowlist", "whitelist", "app-installation", "installation von apps", "app allow", "app block", "app control", "app installer", "ms-appinstaller", "active x", "activex", "vbscript", "scriptlets", "xaml", "mark of the web", "ausführungskontrolle", "ausfuehrungskontrolle", "skripte", "scripts", "powershell", "erlaubte programme"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_APP_COMPLIANCE", ("requiredApps",), "Windows app compliance can require managed applications."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_APP_CONTROL", ("appControlId", "fileBaseInfo"), "Windows App Control is relevant to execution-control requirements."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CUSTOM_CSP", ("installSyncML",), "Relution Windows CSP evidence includes PowerShell and application-control policy nodes."),
            semantic_target(("MACOS",), "relution-native", "MACOS_APP_COMPLIANCE", ("requiredApps",), "macOS app compliance can require managed applications."),
            semantic_target(("MACOS",), "apple-schema-profile", "profile:com.apple.applicationaccess.new", ("familyControlsEnabled", "pathBlackList", "pathWhiteList"), "Apple application restrictions can represent app allow/deny decisions."),
            semantic_target(("IOS",), "relution-native", "IOS_APP_COMPLIANCE", ("requiredApps", "whitelistedApps", "isBlacklist"), "iOS app compliance can require or restrict managed apps."),
            semantic_target(("IOS",), "relution-native", "IOS_MANAGED_APP", ("bundleId", "content"), "iOS managed app configuration can scope app policy."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", ANDROID_PLAY_STORE, ("restrictedPlayStoreMode", "appAutoUpdatePolicy"), "Managed Play can restrict app availability and update policy."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_APP_POLICY", ("applications",), "Android Enterprise app policy can configure managed application scope."),
        ),
        ("KONF.6.1", "KONF.6.4", "BER.5.1"),
    ),
    SemanticConceptRule(
        "permissions_privacy",
        "Berechtigungen und Datenschutz",
        "Permissions and privacy",
        ("berechtigung", "berechtigungen", "permission", "permissions", "datenschutz", "privacy", "privileg", "zugriffsrecht", "zugriffsrechte", "tcc"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_RESTRICTION", ("allowPrivacy", "allowPrivacyExperience", "allowSyncMySettings"), "Windows restrictions expose privacy-related toggles."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_LOCAL_DEVICE_SECURITY", ("allowLocalAdminAccounts", "allowGuestAccounts"), "Windows local security policy can restrict local account privileges."),
            semantic_target(("MACOS",), "apple-mobileconfig", "com.apple.TCC.configuration-profile-policy", ("service", "authorization"), "Apple PPPC profiles can govern macOS privacy permissions."),
            semantic_target(("MACOS",), "relution-native", "MACOS_RESTRICTION", ("allowCamera", "allowCloudDocumentSync"), "macOS restrictions expose privacy-relevant toggles."),
            semantic_target(("IOS",), "relution-native", "IOS_RESTRICTION", ("allowCloudPrivateRelay", "allowFindMyFriendsModification", "allowCamera"), "iOS restrictions expose privacy-relevant toggles."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_PERMISSION_MANAGEMENT", ("defaultPermissionPolicy", "wellKnownPermissions", "customPermissions"), "Android Enterprise permission policy can manage app permissions."),
        ),
        ("KONF.6.1", "KONF.6.4", "BER.5.1"),
    ),
    SemanticConceptRule(
        "cloud_sync",
        "Cloud- und Synchronisationsfunktionen",
        "Cloud and sync functions",
        ("cloud", "icloud", "online-funktionen", "online funktionen", "synchronisation", "synchronisierung", "sync", "handoff", "continuity", "onedrive", "microsoft cloud"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_RESTRICTION", ("allowSyncMySettings", "allowAddingForeignAccountsManually", "allowAccounts"), "Windows restrictions can reduce Microsoft account and sync surfaces."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CUSTOM_CSP", ("installSyncML",), "Relution Windows CSP evidence includes Microsoft cloud and sync-related policies."),
            semantic_target(("MACOS",), "relution-native", "MACOS_RESTRICTION", ("allowCloudDocumentSync", "allowCloudKeychainSync", "allowCloudPhotoLibrary"), "macOS restrictions can disable iCloud sync surfaces."),
            semantic_target(("MACOS",), "apple-schema-profile", APPLE_APPLICATION_ACCESS, ("allowCloudDocumentSync", "allowCloudPhotoLibrary", "allowCloudDesktopAndDocuments"), "Apple restrictions schema covers iCloud sync controls."),
            semantic_target(("IOS",), "relution-native", "IOS_RESTRICTION", ("allowCloudBackup", "allowCloudDocumentSync", "allowCloudKeychainSync", "allowCloudPhotoLibrary"), "iOS restrictions can disable iCloud sync surfaces."),
            semantic_target(("IOS", "MACOS"), "apple-schema-profile", APPLE_APPLICATION_ACCESS, ("allowCloudPhotoLibrary", "allowActivityContinuation"), "Apple restrictions schema covers iCloud and Continuity controls."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_PERSONAL_USAGE", ("accountTypesWithManagementDisabled", "personalPlayStoreMode"), "Android Enterprise personal-usage controls can reduce personal cloud account surfaces."),
        ),
        ("ASST.3.10", "KONF.11.8"),
    ),
    SemanticConceptRule(
        "telemetry",
        "Telemetrie und Diagnosedaten",
        "Telemetry and diagnostics",
        ("telemetrie", "telemetry", "diagnose", "diagnostic", "analytics", "connected user experience", "cuet", "usage data", "feedback notifications", "online tips", "search highlights", "news and interests", "suggested apps", "consumer experiences", "personalized recommendations"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_RESTRICTION", ("allowPrivacy", "allowPrivacyExperience"), "Windows restrictions expose privacy and telemetry-adjacent controls."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CUSTOM_CSP", ("installSyncML",), "Relution Windows CSP evidence includes telemetry and diagnostic policy nodes."),
            semantic_target(("MACOS", "IOS"), "apple-schema-profile", APPLE_APPLICATION_ACCESS, ("allowDiagnosticSubmission",), "Apple restrictions schema covers diagnostic submission."),
            semantic_target(("MACOS",), "relution-native", "MACOS_RESTRICTION", ("allowAppleIntelligenceReport",), "macOS restrictions expose diagnostic and report-related toggles."),
            semantic_target(("IOS",), "relution-native", "IOS_RESTRICTION", ("allowAppleIntelligenceReport",), "iOS restrictions expose diagnostic and report-related toggles."),
        ),
        ("DET.3.4", "DET.4.4"),
    ),
    SemanticConceptRule(
        "lock_screen_message",
        "Sperrbildschirm- und Anmeldemeldungen",
        "Lock-screen and login messages",
        ("lock screen message", "if lost return", "if lost return to", "lost return", "consent message", "login message", "logon message", "device owner lock screen", "support message", "sperrbildschirmmeldung", "anmeldemeldung", "hinweis auf dem sperrbildschirm"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_LOCAL_DEVICE_SECURITY", ("loginMessageTitle", "loginMessageText"), "Windows local security policy can publish a logon message once organization text is supplied."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_WALLPAPER", ("lockScreenText",), "Windows wallpaper policy can publish lock-screen text where that surface is preferred."),
            semantic_target(("MACOS",), "relution-native", "MACOS_LOGIN_WINDOW", ("loginWindow.loginWindowText",), "macOS Login Window can publish a login message once organization text is supplied."),
            semantic_target(("MACOS",), "relution-native", "MACOS_SECURITY_PREFERENCES", ("dontAllowLockMessageUI",), "macOS security preferences can protect lock-message modification, but not supply the message text by itself."),
            semantic_target(("IOS",), "relution-native", "IOS_SHARED_DEVICE", ("lockScreenFootnote",), "iOS shared-device settings can display a lock-screen footnote once organization text is supplied."),
            semantic_target(("IOS",), "apple-mobileconfig", "com.apple.shareddeviceconfiguration", ("ifLostReturnToMessage", "lockScreenFootnote"), "Relution can import shared-device lock-screen message payloads; exact text is organization-specific."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_LOCK_SCREEN_MESSAGES", ("deviceOwnerLockScreenInfo.defaultMessage", "shortSupportMessage.defaultMessage", "longSupportMessage.defaultMessage"), "Android Enterprise lock-screen messages can display owner and support text once local wording is supplied."),
        ),
        ("KONF.3.6", "ASST.6.1"),
    ),
    SemanticConceptRule(
        "time_sync",
        "Zeit- und Zeitsynchronisation",
        "Time and time synchronization",
        ("time service", "automatic date", "date and time automatically", "network-provided time", "auto date", "ntp", "zeitquelle", "zeitquellen", "zeitsynchronisation", "automatische uhrzeit", "datum und uhrzeit"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_RESTRICTION", ("allowTimeAndLanguage", "allowDateTime"), "Windows restrictions can limit user changes to time and language settings."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CUSTOM_CSP", ("installSyncML",), "Relution Windows CSP evidence can carry Windows time-service policy nodes."),
            semantic_target(("IOS", "MACOS"), "relution-native", "APPLE_TIME_ZONE", ("timeZone",), "Apple Time Zone can configure a managed time zone when local policy requires it."),
            semantic_target(("IOS",), "relution-native", "IOS_RESTRICTION", ("forceAutomaticDateAndTime",), "iOS restrictions can force automatic date and time."),
            semantic_target(("IOS", "MACOS"), "apple-schema-profile", APPLE_APPLICATION_ACCESS, ("forceAutomaticDateAndTime",), "Apple restrictions schema can force automatic date and time where supported."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_SYSTEM_CLOCK_MANAGEMENT", ("autoTimeRequired",), "Android Enterprise system clock management can require automatic time."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", ANDROID_RESTRICTION, ("androidAutoDateAndTimeZoneSetting", "autoTimeRequired"), "Android Enterprise restrictions can enforce automatic date/time behavior."),
        ),
        ("KONF.4.5",),
    ),
    SemanticConceptRule(
        "exploit_mitigation",
        "Exploit-Mitigation und Laufzeitschutz",
        "Exploit mitigation and runtime protection",
        ("ausnutzung von schwachstellen", "exploit", "exploit protection", "aslr", "dep", "nx", "sehop", "structured exception handling", "heap", "kernel", "runtime protection", "memory protection", "schutzmechanismen"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CUSTOM_CSP", ("installSyncML",), "Relution Windows CSP evidence can carry Exploit Protection, SEHOP, Defender, and runtime-hardening policy nodes."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_ANTIVIRUS", ("enableNetworkProtection", "allowIOAVProtection", "puaProtection"), "Windows Antivirus settings are adjacent to exploit and runtime protection when Defender controls are involved."),
            semantic_target(("MACOS",), "relution-native", "MACOS_SYSTEM_POLICY_CONTROL", ("enableAssessment", "allowIdentifiedDevelopers"), "macOS system policy controls support platform runtime trust decisions."),
            semantic_target(("MACOS",), "relution-native", "MACOS_SECURITY_PREFERENCES", ("dontAllowPasswordResetUI", "dontAllowFireWallUI"), "macOS security preferences can protect selected security-control surfaces but do not model ASLR/DEP directly."),
            semantic_target(("IOS",), "relution-native", "IOS_RESTRICTION", ("allowEnterpriseAppTrust", "allowUIConfigurationProfileInstallation"), "iOS restrictions can reduce unmanaged trust surfaces, but exploit mitigations are mainly OS built-ins."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", ANDROID_ADVANCED_SECURITY, ("developerSettings", "commonCriteriaMode", "untrustedAppsPolicy"), "Android Enterprise advanced security can reduce exploit-enabling surfaces such as developer mode and untrusted app installation."),
        ),
        ("KONF.7.6", "KONF.7.9", "KONF.7.10"),
    ),
    SemanticConceptRule(
        "device_attestation_posture",
        "Geräteintegrität und Attestation",
        "Device integrity and attestation",
        ("hardware-backed key attestation", "hbka", "security posture", "bootloader", "locked bootloader", "unknown os", "advanced protection", "high-risk users", "high risk users", "system integrity protection", "sip", "signed system volume", "ssv", "platform integrity", "device integrity", "attestation"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_BITLOCKER", ("requireDeviceEncryption", "tpmStartup"), "Windows BitLocker and TPM-backed startup settings are relevant device-integrity surfaces."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CUSTOM_CSP", ("installSyncML",), "Relution Windows CSP evidence can carry Secure Boot, TPM, and virtualization-based security posture nodes."),
            semantic_target(("MACOS",), "relution-native", "MACOS_SYSTEM_POLICY_CONTROL", ("enableAssessment", "allowIdentifiedDevelopers"), "macOS system policy control is adjacent to platform integrity checks."),
            semantic_target(("MACOS",), "relution-native", "MACOS_LOGIN_WINDOW", ("loginWindow.disableFDEAutoLogin",), "macOS login-window controls can support secure startup behavior but do not expose SIP/SSV toggles directly."),
            semantic_target(("IOS",), "relution-native", "IOS_RESTRICTION", ("allowUIConfigurationProfileInstallation",), "iOS restrictions can reduce unmanaged profile changes, while attestation remains an MDM/device-state concern."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", ANDROID_ADVANCED_SECURITY, ("commonCriteriaMode", "developerSettings", "untrustedAppsPolicy"), "Android Enterprise advanced security settings are relevant to posture, bootloader, and high-risk user hardening."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_COMPLIANCE_ENFORCEMENT", ("configurationEnforcementRules",), "Android Enterprise compliance enforcement can react to posture or integrity failures once local rules are defined."),
        ),
        ("ASST.4.2", "DET.5.10"),
    ),
    SemanticConceptRule(
        "camera_microphone",
        "Kamera und Mikrofon",
        "Camera and microphone",
        ("kamera", "camera", "mikrofon", "microphone", "sprachassistent", "siri", "cortana", "assistant"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_RESTRICTION", ("allowCamera", "allowCortana"), "Windows restrictions can disable camera and assistant surfaces; microphone needs separate local validation."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CUSTOM_CSP", ("installSyncML",), "Relution Windows CSP evidence includes lock-screen camera and assistant-related policies."),
            semantic_target(("MACOS",), "relution-native", "MACOS_RESTRICTION", ("allowCamera",), "macOS restrictions can disable camera; microphone requires PPPC or local policy scope."),
            semantic_target(("MACOS",), "apple-mobileconfig", "com.apple.TCC.configuration-profile-policy", ("service", "authorization"), "Apple PPPC can govern microphone/camera permissions for specific apps."),
            semantic_target(("IOS",), "relution-native", "IOS_RESTRICTION", ("allowCamera", "allowAssistant", "allowAssistantWhileLocked"), "iOS restrictions can disable camera and assistant surfaces."),
            semantic_target(("IOS", "MACOS"), "apple-schema-profile", APPLE_APPLICATION_ACCESS, ("allowCamera", "allowAssistant", "allowAssistantWhileLocked"), "Apple restrictions schema includes camera and assistant controls."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_DISABLE_CAMERAS", ("cameraDisabled",), "Android Enterprise can disable cameras; microphone access is a separate permission-management decision."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_SYSTEM_AUDIO_MANAGEMENT", ("unmuteMicrophoneDisabled",), "Android Enterprise system audio management can affect microphone state."),
        ),
        ("KONF.3.7", "SENS.7.18"),
    ),
    SemanticConceptRule(
        "location",
        "Standort und Ortung",
        "Location",
        ("standort", "ortung", "location service", "location services", "location sharing", "location is set to enabled", "find my", "geofencing", "gps"),
        (
            semantic_target(("IOS",), "relution-native", "IOS_RESTRICTION", ("allowFindMyFriendsModification",), "iOS restrictions can limit Find My modification surfaces."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", ANDROID_LOCATION, ("locationMode",), "Android Enterprise location sharing management covers location state."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_PERSONAL_USAGE", ("personalPlayStoreMode",), "Personal-usage controls can scope personal location-related services."),
        ),
        ("SENS.7.18",),
    ),
    SemanticConceptRule(
        "security_critical_functions",
        "Sicherheitskritische Funktionen",
        "Security-critical functions",
        ("sicherheitskritische funktionen", "security-critical functions", "ortungsdienste", "automatisch geoeffnet", "automatisch geöffnet", "automatisch ausgefuehrt", "automatisch ausgeführt", "remote apple events", "screen sharing", "bildschirmfreigabe"),
        (
            semantic_target(("MACOS",), "relution-native", "MACOS_RESTRICTION", ("allowRemoteScreenObservation", "allowARDRemoteManagementModification", "allowRemoteAppleEventsModification"), "macOS restrictions can disable selected security-critical remote-observation and remote-control surfaces."),
            semantic_target(("MACOS",), "relution-native", "MACOS_SECURITY_PREFERENCES", ("dontAllowFireWallUI", "dontAllowLockMessageUI"), "macOS security preferences can protect user-facing security controls."),
            semantic_target(("MACOS",), "relution-native", "MACOS_SYSTEM_POLICY_CONTROL", ("allowIdentifiedDevelopers", "enableAssessment"), "macOS system policy control supports platform trust and execution-control decisions."),
        ),
    ),
    SemanticConceptRule(
        "remote_lock_wipe",
        "Fernlöschung und Sperre",
        "Remote lock and wipe",
        ("fernlöschung", "fernloeschung", "remote wipe", "remote lock", "außerbetriebnahme", "ausserbetriebnahme", "verlust", "abhandenkommen", "erase content"),
        (
            semantic_target(("IOS",), "apple-schema-profile", APPLE_APPLICATION_ACCESS, ("allowEraseContentAndSettings",), "Apple restrictions schema can restrict local erase actions; remote wipe remains an MDM operation."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_COMPLIANCE_ENFORCEMENT", ("configurationEnforcementRules",), "Android Enterprise compliance enforcement can trigger actions after policy violations."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_COMPANION", ("actionTimeout", "pollInterval"), "Windows companion behavior is adjacent to remote management timing, not exact wipe semantics."),
        ),
        ("KONF.3.6", "ASST.6.1"),
    ),
    SemanticConceptRule(
        "logging_compliance",
        "Protokollierung und Compliance",
        "Logging and compliance",
        ("protokoll", "protokollierung", "logging", "audit policy", "auditpol", "event log", "überwachung", "ueberwachung", "monitoring", "compliance", "gerätestatus", "geraetestatus", "policy violation", "sicherheitsereignis"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CUSTOM_CSP", ("installSyncML",), "Relution Windows CSP evidence includes audit, event-log, and PowerShell logging policy nodes."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_COMPANION", ("logLevel", "pollInterval"), "Windows companion settings expose device-management polling and logging knobs."),
            semantic_target(("MACOS",), "relution-native", "MACOS_APP_COMPLIANCE", ("requiredApps",), "macOS app compliance is a candidate compliance surface."),
            semantic_target(("IOS",), "relution-native", "IOS_APP_COMPLIANCE", ("requiredApps", "uninstallForbiddenApps"), "iOS app compliance is a candidate compliance surface."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_COMPLIANCE_ENFORCEMENT", ("configurationEnforcementRules",), "Android Enterprise compliance enforcement can react to policy violations."),
        ),
        ("DET.3.4", "DET.4.4", "KONF.2.5"),
    ),
    SemanticConceptRule(
        "inventory",
        "Inventarisierung",
        "Inventory",
        ("inventar", "inventarisierung", "asset", "geräteinventar", "geraeteinventar", "systeminventar", "anwendungsinventar"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_COMPANION", ("pollInterval", "manageWingetDependencies"), "Relution companion policy is adjacent to inventory and dependency management."),
            semantic_target(("MACOS",), "relution-native", "MACOS_APP_COMPLIANCE", ("requiredApps",), "macOS app compliance can support application inventory checks."),
            semantic_target(("IOS",), "relution-native", "IOS_APP_COMPLIANCE", ("requiredApps",), "iOS app compliance can support application inventory checks."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_COMPLIANCE_ENFORCEMENT", ("configurationEnforcementRules",), "Android Enterprise compliance can act on inventory-derived state."),
        ),
        ("ASST.2.2", "ASST.2.3"),
    ),
    SemanticConceptRule(
        "browser_restrictions",
        "Browser- und Webeinschränkungen",
        "Browser and web restrictions",
        ("browser", "webbrowser", "safari", "edge", "smartscreen", "webseiten", "webseitenfilter", "web filter", "cookie", "history", "web content"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CUSTOM_CSP", ("installSyncML",), "Relution Windows CSP evidence includes Edge, Browser, InternetExplorer, and SmartScreen policies."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_NETWORK_PROXY", ("useProxyServer", "proxyServer"), "Windows proxy policy can support web access controls."),
            semantic_target(("MACOS",), "relution-native", "MACOS_PARENTAL_CONTROLS", ("contentFilter", "contentFilter.restrictWeb"), "macOS parental controls can restrict web content."),
            semantic_target(("IOS",), "relution-native", "IOS_WEB_CONTENT_FILTER", ("filterType", "autoFilterEnabled", "blacklistedUrls", "permittedUrls"), "iOS web content filter can enforce managed web restrictions."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_RECOMMENDED_GLOBAL_PROXY", ("proxyType", "host", "port", "pacUri"), "Android Enterprise global proxy is a candidate for web filtering architecture."),
        ),
        ("KONF.6.14", "KONF.12.3", "KONF.12.6"),
    ),
    SemanticConceptRule(
        "external_media",
        "Externe Medien und Schnittstellen",
        "External media and peripherals",
        ("externe medien", "wechseldatenträger", "wechseldatentraeger", "usb", "peripherie", "removable", "removable media", "external drive", "host-system", "host system", "pairing"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_BITLOCKER", ("removableDrivesEncryptionType", "removableDrivesConfigureRecovery"), "BitLocker can enforce removable-drive encryption choices."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_RESTRICTION", ("allowBluetooth", "allowVPNOverCellular"), "Windows restrictions expose selected peripheral and connectivity controls."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CUSTOM_CSP", ("installSyncML",), "Relution Windows CSP evidence includes removable-storage audit and encryption nodes."),
            semantic_target(("MACOS",), "relution-native", "MACOS_FINDER", ("showExternalHardDrivesOnDesktop", "showRemovableMediaOnDesktop"), "macOS Finder policy is adjacent to removable media behavior."),
            semantic_target(("IOS", "MACOS"), "apple-schema-profile", APPLE_APPLICATION_ACCESS, ("allowFilesUSBDriveAccess", "allowHostPairing"), "Apple restrictions schema can disable USB drive access and host pairing where supported."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_DEVICE_CONNECTIVITY", ("usbDataAccess", "bluetoothSharing"), "Android Enterprise connectivity policy can restrict USB data and Bluetooth sharing."),
        ),
        ("ASST.4.1", "KONF.3.7", "KONF.11.8"),
    ),
    SemanticConceptRule(
        "kiosk",
        "Kiosk und App Lock",
        "Kiosk and app lock",
        ("kiosk", "app lock", "single app", "einzel-app", "supervised", "shared device", "gesicherter shared device"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_KIOSK_MODE", ("kioskModeType", "kioskAppType", "edgeKioskURL"), "Windows kiosk mode can restrict device interaction to approved apps or URLs."),
            semantic_target(("IOS",), "relution-native", "IOS_APP_LOCK", ("identifier", "disableTouch", "disableAutoLock"), "iOS App Lock can enforce single-app behavior."),
            semantic_target(("IOS",), "relution-native", "IOS_SECURED_SHARED_DEVICE", ("relutionClientAppIdentifier", "disableTouch"), "iOS secured shared-device settings can restrict shared devices."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_KIOSK_MODE", ("kioskCustomLauncher", "systemNavigation", "statusBar"), "Android Enterprise kiosk mode can restrict device interaction."),
        ),
    ),
    SemanticConceptRule(
        "managed_data_flow",
        "Managed Open-In und Datenfluss",
        "Managed data flow",
        ("managed open", "managed pasteboard", "copy/paste", "pasteboard", "datenfluss", "unmanaged", "managed domains", "corporate documents", "dienstliche daten"),
        (
            semantic_target(("IOS",), "relution-native", "IOS_MANAGED_DOMAINS", ("emailDomains", "webDomains"), "iOS managed domains can scope managed data flow."),
            semantic_target(("IOS", "MACOS"), "apple-schema-profile", APPLE_APPLICATION_ACCESS, ("requireManagedPasteboard", "allowOpenFromManagedToUnmanaged", "allowOpenFromUnmanagedToManaged"), "Apple restrictions schema covers managed pasteboard and open-in controls."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_PERSONAL_USAGE", ("personalApplications", "personalPlayStoreMode"), "Android Enterprise personal-usage controls help separate work and personal data flow."),
        ),
        ("KONF.11.8",),
    ),
    SemanticConceptRule(
        "policy_governance",
        "Richtlinien und Governance",
        "Policy and governance",
        ("richtlinie", "richtlinien", "sicherheitsrichtlinie", "sicherheitsrichtlinien", "interne richtlinien", "security policy", "local security policy", "policy governance", "nutzung und kontrolle der geraete", "nutzung und kontrolle der geräte", "kontrolle der geraete", "kontrolle der geräte", "control of devices", "regelungen"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_LOCAL_DEVICE_SECURITY", ("allowLocalAdminAccounts", "allowGuestAccounts", "loginMessageText"), "Windows local security policy supports documented governance decisions for managed clients."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_RESTRICTION", ("allowSettings", "allowAccounts", "allowPrivacy"), "Windows restrictions can implement selected policy decisions once local scope is known."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_APP_COMPLIANCE", ("requiredApps",), "Windows app compliance can support policy checks for required managed software."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CUSTOM_CSP", ("installSyncML",), "Windows Custom CSP can carry organization-specific security policy settings."),
            semantic_target(("MACOS",), "relution-native", "MACOS_RESTRICTION", ("allowCamera", "allowCloudDocumentSync", "allowDiagnosticSubmission"), "macOS restrictions can implement selected policy decisions once local scope is known."),
            semantic_target(("MACOS",), "relution-native", "MACOS_SECURITY_PREFERENCES", ("dontAllowFireWallUI", "dontAllowLockMessageUI"), "macOS security preferences can protect locally governed security settings."),
            semantic_target(("MACOS",), "relution-native", "MACOS_SYSTEM_POLICY_CONTROL", ("allowIdentifiedDevelopers", "enableAssessment"), "macOS system policy control supports platform trust decisions."),
            semantic_target(("MACOS",), "relution-native", "MACOS_APP_COMPLIANCE", ("requiredApps",), "macOS app compliance can support policy checks for required managed software."),
            semantic_target(("IOS",), "relution-native", "IOS_RESTRICTION", ("allowAppInstallation", "allowCamera", "allowCloudBackup"), "iOS restrictions can implement selected policy decisions once local scope is known."),
            semantic_target(("IOS",), "relution-native", "IOS_APP_COMPLIANCE", ("requiredApps", "whitelistedApps", "uninstallForbiddenApps"), "iOS app compliance can support policy checks for required or forbidden apps."),
            semantic_target(("IOS",), "relution-native", "IOS_SHARED_DEVICE", ("assetTagInformation", "lockScreenFootnote"), "iOS shared-device settings can surface organization policy context on managed devices."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_RESTRICTION", ("installAppsDisabled", "uninstallAppsDisabled", "screenCaptureDisabled"), "Android Enterprise restrictions can implement selected policy decisions once local scope is known."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_COMPLIANCE_ENFORCEMENT", ("configurationEnforcementRules",), "Android Enterprise compliance enforcement can support governance checks and reactions."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_APP_POLICY", ("applications",), "Android Enterprise app policy can support governed app scope."),
        ),
    ),
    SemanticConceptRule(
        "mdm_strategy_selection",
        "MDM-Strategie und Produktauswahl",
        "MDM strategy and product selection",
        ("mdm-strategie", "mdm strategie", "strategie fuer das mobile device management", "strategie für das mobile device management", "strategie zur ios-nutzung", "ios-nutzung", "ios nutzung", "auswahl eines mdm-produkts", "auswahl eines mdm produkts", "mdm-produkt", "mdm produkt", "mdm product", "mdm-software", "mdm software", "mobile device management", "managementsystem", "verwaltungssoftware", "mdm"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_COMPANION", ("enabled", "pollInterval", "manageWingetDependencies"), "Windows companion settings are a Relution management-support surface, not an exact MDM strategy implementation."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_APP_COMPLIANCE", ("requiredApps",), "Windows app compliance can support MDM strategy checks for required software."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CUSTOM_CSP", ("installSyncML",), "Windows Custom CSP can support strategy-specific policy requirements."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_RESTRICTION", ("allowManualUnenrollment", "allowSettings"), "Windows restrictions can support selected management strategy constraints."),
            semantic_target(("MACOS",), "relution-native", "MACOS_APP_COMPLIANCE", ("requiredApps",), "macOS app compliance can support MDM strategy checks for required software."),
            semantic_target(("MACOS",), "relution-native", "MACOS_ACCOUNT_SETUP", ("accountSetupConfiguration.primaryAccountManaged", "accountSetupConfiguration.primaryAccountAdmin"), "macOS account setup can support managed onboarding decisions."),
            semantic_target(("MACOS",), "relution-native", "MACOS_RESTRICTION", ("allowCloudDocumentSync", "allowDiagnosticSubmission"), "macOS restrictions can support selected management strategy constraints."),
            semantic_target(("IOS",), "relution-native", "IOS_APP_COMPLIANCE", ("requiredApps", "disableAll", "whitelistedApps"), "iOS app compliance can support MDM strategy checks for required or allowed apps."),
            semantic_target(("IOS",), "relution-native", "IOS_RESTRICTION", ("allowUIConfigurationProfileInstallation", "allowAppInstallation", "allowOpenFromManagedToUnmanaged"), "iOS restrictions can support selected MDM strategy constraints."),
            semantic_target(("IOS",), "relution-native", "IOS_SECURED_SHARED_DEVICE", ("relutionClientAppIdentifier", "enforceLoginViaAppLock"), "iOS secured shared-device settings can support managed device strategy decisions."),
            semantic_target(("IOS",), "relution-native", "IOS_SHARED_DEVICE", ("assetTagInformation", "lockScreenFootnote"), "iOS shared-device settings can support device identification and user-facing policy context."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_COMPLIANCE_ENFORCEMENT", ("configurationEnforcementRules",), "Android Enterprise compliance enforcement is a management-support surface for MDM strategy checks."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_APP_POLICY", ("applications", "connectedWorkAndPersonalApp"), "Android Enterprise app policy can support strategy-specific app scope."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_ADVANCED_SECURITY_OVERRIDES", ("untrustedAppsPolicy", "googlePlayProtectVerifyApps", "encryptionPolicy"), "Android Enterprise advanced security can support MDM product requirement checks."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_RESTRICTION", ("installAppsDisabled", "uninstallAppsDisabled", "modifyAccountsDisabled"), "Android Enterprise restrictions can support selected MDM strategy constraints."),
        ),
    ),
    SemanticConceptRule(
        "device_onboarding",
        "Geräte-Onboarding und Enrollment",
        "Device onboarding and enrollment",
        ("bereitstellen", "bereitstellt", "enrollment", "registrierung", "geraeteregistrierung", "geräteregistrierung", "device enrollment", "onboarding", "installation des mdm-clients", "installation des mdm clients", "mdm-client", "mdm client", "verteilung", "verteilt werden", "deployment"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_COMPANION", ("enabled", "appInstallationTimeout", "pollAfterMinutes"), "Windows companion settings can support managed-device rollout behavior."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_APP_COMPLIANCE", ("requiredApps",), "Windows app compliance can require onboarding support software."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_RESTRICTION", ("allowManualUnenrollment",), "Windows restrictions can support managed enrollment constraints."),
            semantic_target(("MACOS",), "relution-native", "MACOS_ACCOUNT_SETUP", ("accountSetupConfiguration.primaryAccountManaged", "accountSetupConfiguration.primaryAccountShortName"), "macOS account setup can support managed device onboarding."),
            semantic_target(("MACOS",), "relution-native", "MACOS_APP_COMPLIANCE", ("requiredApps",), "macOS app compliance can require onboarding support software."),
            semantic_target(("IOS",), "relution-native", "IOS_SECURED_SHARED_DEVICE", ("relutionClientAppIdentifier", "enforceLoginViaAppLock"), "iOS secured shared-device settings can support managed onboarding workflows."),
            semantic_target(("IOS",), "relution-native", "IOS_SHARED_DEVICE", ("assetTagInformation", "lockScreenFootnote"), "iOS shared-device settings can support device identification during onboarding."),
            semantic_target(("IOS",), "relution-native", "IOS_APP_COMPLIANCE", ("requiredApps",), "iOS app compliance can require MDM client or onboarding support apps."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_COMPLIANCE_ENFORCEMENT", ("configurationEnforcementRules",), "Android Enterprise compliance enforcement can support onboarding completion checks."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_APP_POLICY", ("applications",), "Android Enterprise app policy can deploy onboarding support apps."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_RESTRICTION", ("factoryResetDisabled", "removeUserDisabled"), "Android Enterprise restrictions can support managed enrollment constraints."),
        ),
    ),
    SemanticConceptRule(
        "reference_configuration_rollout",
        "Referenzkonfiguration und Änderungsrollout",
        "Reference configuration and change rollout",
        ("grundkonfiguration", "referenzinstallation", "referenzumgebung", "referenzkonfiguration", "reference installation", "reference configuration", "konfigurationsaenderung", "konfigurationsaenderungen", "konfigurationsänderung", "konfigurationsänderungen", "sicherheitskonfiguration", "zentralisiert verteilt", "change rollout", "rollout"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CUSTOM_CSP", ("installSyncML",), "Windows Custom CSP can distribute organization-specific reference configuration settings."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_LOCAL_DEVICE_SECURITY", ("allowLocalAdminAccounts", "inactivityTimeUntilScreenSaver", "lanManagerAuthenticationLvl"), "Windows local security policy can support reference security configuration."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_RESTRICTION", ("allowSettings", "allowPrivacy", "allowUpdateAndSecurity"), "Windows restrictions can support reference configuration decisions."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_COMPANION", ("pollInterval", "appInstallationTimeout"), "Windows companion settings can support rollout timing and managed app changes."),
            semantic_target(("MACOS",), "relution-native", "MACOS_SECURITY_PREFERENCES", ("dontAllowFireWallUI", "dontAllowLockMessageUI"), "macOS security preferences can lock selected reference security settings."),
            semantic_target(("MACOS",), "relution-native", "MACOS_SYSTEM_POLICY_CONTROL", ("allowIdentifiedDevelopers", "enableAssessment"), "macOS system policy control can support reference platform-trust configuration."),
            semantic_target(("MACOS",), "relution-native", "MACOS_RESTRICTION", ("allowCloudDocumentSync", "allowCamera", "allowDiagnosticSubmission"), "macOS restrictions can support reference configuration decisions."),
            semantic_target(("MACOS",), "relution-native", "MACOS_APP_COMPLIANCE", ("requiredApps",), "macOS app compliance can support reference software baselines."),
            semantic_target(("IOS",), "relution-native", "IOS_RESTRICTION", ("allowAppInstallation", "allowCloudBackup", "allowUIConfigurationProfileInstallation"), "iOS restrictions can support reference configuration decisions."),
            semantic_target(("IOS",), "relution-native", "IOS_APP_COMPLIANCE", ("requiredApps", "whitelistedApps"), "iOS app compliance can support reference software baselines."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_RESTRICTION", ("installAppsDisabled", "uninstallAppsDisabled", "vpnConfigDisabled"), "Android Enterprise restrictions can support reference configuration decisions."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_ADVANCED_SECURITY_OVERRIDES", ("untrustedAppsPolicy", "googlePlayProtectVerifyApps", "encryptionPolicy"), "Android Enterprise advanced security can support reference security configuration."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_COMPLIANCE_ENFORCEMENT", ("configurationEnforcementRules",), "Android Enterprise compliance enforcement can monitor reference configuration state."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_APP_POLICY", ("applications",), "Android Enterprise app policy can support reference software baselines."),
        ),
    ),
    SemanticConceptRule(
        "administration_procedures",
        "Administrationsverfahren",
        "Administration procedures",
        (
            "administrationsverfahren",
            "administrationsprozess",
            "administration",
            "administriert",
            "administrative procedures",
            "admin procedures",
            "verwaltung der sicherheitsrichtlinien",
            "lokale sicherheitsrichtlinien",
            "sicherheitsmanagement",
            "betriebsdokumentation",
            "betriebliche aufgaben",
        ),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_LOCAL_DEVICE_SECURITY", ("allowLocalAdminAccounts", "requireCtrlAltDelToLogon", "loginMessageText"), "Windows local security policy can support administration-procedure constraints."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CUSTOM_CSP", ("installSyncML",), "Windows Custom CSP can carry administrative hardening settings."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_COMPANION", ("logLevel", "pollInterval"), "Windows companion settings expose management polling and logging support."),
            semantic_target(("MACOS",), "relution-native", "MACOS_ACCOUNT_SETUP", ("accountSetupConfiguration.primaryAccountAdmin", "accountSetupConfiguration.adminAccountHidden"), "macOS account setup can support administrative account procedures."),
            semantic_target(("MACOS",), "relution-native", "MACOS_SECURITY_PREFERENCES", ("dontAllowFireWallUI", "dontAllowPasswordResetUI"), "macOS security preferences can protect administrative security changes."),
            semantic_target(("MACOS",), "relution-native", "MACOS_SYSTEM_POLICY_CONTROL", ("allowIdentifiedDevelopers", "enableAssessment"), "macOS system policy control supports administrative platform-trust decisions."),
            semantic_target(("IOS",), "relution-native", "IOS_RESTRICTION", ("allowUIConfigurationProfileInstallation", "allowEraseContentAndSettings"), "iOS restrictions can limit administrative profile and erase actions."),
            semantic_target(("IOS",), "relution-native", "IOS_APP_COMPLIANCE", ("requiredApps", "uninstallForbiddenApps"), "iOS app compliance can support administrative software requirements."),
            semantic_target(("IOS",), "relution-native", "IOS_SECURED_SHARED_DEVICE", ("enforceLoginViaAppLock", "disableSsoLogin"), "iOS secured shared-device settings can support controlled administrative use."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_RESTRICTION", ("modifyAccountsDisabled", "credentialsConfigDisabled", "factoryResetDisabled"), "Android Enterprise restrictions can support administrative procedure constraints."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_COMPLIANCE_ENFORCEMENT", ("configurationEnforcementRules",), "Android Enterprise compliance enforcement can support administrative checks."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_ADVANCED_SECURITY_OVERRIDES", ("developerSettings", "commonCriteriaMode"), "Android Enterprise advanced security can support administrative hardening settings."),
        ),
    ),
    SemanticConceptRule(
        "hardened_device_procurement",
        "Abgesicherte Geräte und Beschaffung",
        "Hardened devices and procurement",
        (
            "besonders abgesicherte endgeraete",
            "besonders abgesicherte endgeräte",
            "besonders abgesicherte mobile endgeraete",
            "besonders abgesicherte mobile endgeräte",
            "abgesicherte endgeraete",
            "abgesicherte endgeräte",
            "geeignete endgeraete",
            "geeignete endgeräte",
            "erlaubte mobile endgeraete",
            "erlaubte mobile endgeräte",
            "aktuelle mac-hardware",
            "aktuelle mac hardware",
            "geeignete windows-version",
            "geeignete windows version",
            "auswahl und beschaffung",
            "beschaffung",
            "procurement",
            "secure hardware",
            "hardened device",
            "hardened devices",
            "latest device architecture",
            "device architecture",
            "current hardware architecture",
            "high-value target",
            "high value target",
            "high-value targets",
            "high value targets",
        ),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_LOCAL_DEVICE_SECURITY", ("allowLocalAdminAccounts", "lanManagerAuthenticationLvl", "onlyElevateSignedValidExecFiles"), "Windows local security policy can support hardened-device baseline decisions."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CUSTOM_CSP", ("installSyncML",), "Windows Custom CSP can support hardware- or edition-specific hardening settings."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_RESTRICTION", ("allowDeveloperUnlock", "allowAllTrustedApps", "allowUpdateAndSecurity"), "Windows restrictions can support hardened device selection constraints."),
            semantic_target(("MACOS",), "relution-native", "MACOS_SYSTEM_POLICY_CONTROL", ("allowIdentifiedDevelopers", "enableAssessment"), "macOS system policy control supports hardened platform-trust decisions."),
            semantic_target(("MACOS",), "relution-native", "MACOS_SECURITY_PREFERENCES", ("dontAllowFireWallUI", "dontAllowPasswordResetUI"), "macOS security preferences can support protected security controls."),
            semantic_target(("MACOS",), "relution-native", "MACOS_RESTRICTION", ("allowCloudDocumentSync", "allowDiagnosticSubmission", "allowAirDrop"), "macOS restrictions can support hardened-device constraints."),
            semantic_target(("MACOS",), "relution-native", "MACOS_APP_COMPLIANCE", ("requiredApps",), "macOS app compliance can support hardened software baselines."),
            semantic_target(("IOS",), "relution-native", "IOS_SECURED_SHARED_DEVICE", ("relutionClientAppIdentifier", "enforceLoginViaAppLock", "disableTouch"), "iOS secured shared-device settings can support hardened shared-device deployments."),
            semantic_target(("IOS",), "relution-native", "IOS_SHARED_DEVICE", ("assetTagInformation", "lockScreenFootnote"), "iOS shared-device settings can identify governed device classes."),
            semantic_target(("IOS",), "relution-native", "IOS_RESTRICTION", ("allowAppInstallation", "allowCloudBackup", "allowScreenShot"), "iOS restrictions can support hardened-device constraints."),
            semantic_target(("IOS",), "relution-native", "IOS_APP_COMPLIANCE", ("requiredApps", "whitelistedApps"), "iOS app compliance can support hardened software baselines."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_ADVANCED_SECURITY_OVERRIDES", ("googlePlayProtectVerifyApps", "commonCriteriaMode", "encryptionPolicy"), "Android Enterprise advanced security can support hardened-device requirements."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_RESTRICTION", ("debuggingFeaturesAllowed", "safeBootDisabled", "screenCaptureDisabled"), "Android Enterprise restrictions can support hardened-device constraints."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_COMPLIANCE_ENFORCEMENT", ("configurationEnforcementRules",), "Android Enterprise compliance enforcement can check hardened-device state."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_APP_POLICY", ("applications",), "Android Enterprise app policy can support hardened software baselines."),
        ),
    ),
    SemanticConceptRule(
        "mdm_compliance",
        "MDM und Compliance",
        "MDM and compliance",
        ("mdm", "mobile device management", "geräteverwaltung", "geraeteverwaltung", "grundkonfiguration", "compliance", "compliant", "regelmäßige überprüfung", "regelmaessige ueberpruefung"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_COMPANION", ("pollInterval", "manageWingetDependencies"), "Windows companion policy is a candidate Relution management surface."),
            semantic_target(("MACOS",), "relution-native", "MACOS_APP_COMPLIANCE", ("requiredApps",), "macOS app compliance is a candidate Relution compliance surface."),
            semantic_target(("IOS",), "relution-native", "IOS_APP_COMPLIANCE", ("requiredApps", "disableAll", "whitelistedApps"), "iOS app compliance is a candidate Relution compliance surface."),
            semantic_target(("ANDROID_ENTERPRISE", "ANDROID"), "relution-native", "ANDROID_ENTERPRISE_COMPLIANCE_ENFORCEMENT", ("configurationEnforcementRules",), "Android Enterprise compliance enforcement is a candidate Relution compliance surface."),
        ),
    ),
    SemanticConceptRule(
        "secure_boot_hardware",
        "Secure Boot und Hardware-Schutz",
        "Secure boot and hardware protection",
        ("secureboot", "secure boot", "tpm", "uefi", "firmware", "boot-schutz", "bootschutz", "bootvorgang", "startup security"),
        (
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_BITLOCKER", ("tpmStartup", "tpmStartupPin", "minimumPinLength"), "Windows BitLocker policy covers TPM-backed startup constraints."),
            semantic_target(("WINDOWS",), "relution-native", "WINDOWS_CUSTOM_CSP", ("installSyncML",), "Relution Windows CSP evidence includes VSM, Secure Boot, and TPM-adjacent baseline nodes."),
            semantic_target(("MACOS",), "relution-native", "MACOS_SYSTEM_POLICY_CONTROL", ("allowIdentifiedDevelopers", "enableAssessment"), "macOS system policy control is adjacent to startup and platform trust."),
            semantic_target(("MACOS",), "apple-schema-profile", "profile:com.apple.preference.security", ("DisableFDEAutoLogin",), "Apple security preferences are a candidate surface for platform security controls."),
        ),
        ("KONF.3.2", "ASST.4.2"),
    ),
)
