import type {
  AppleCompatField,
  AppleCompatFieldKind,
  AppleCompatObjectField,
  AppleCompatScalarFieldKind,
  AppleCompatSetting,
} from "./apple-compat-types.js";
import {
  APPLE_COMMON_PLATFORMS,
  APPLE_PROFILE_SOURCE,
  JAMF_MACOS_UPLOAD_SOURCE,
  JAMF_MOBILE_DEVICE_PROFILES_SOURCE,
} from "./apple-compat-types.js";

export const APPLE_COMPAT_HINT =
  "This setting is not exposed as a dedicated Relution GUI configuration in the harvested server templates. It is exported as an Apple .mobileconfig payload through Relution APPLE_MOBILECONFIG.";

export const APPLE_COMPAT_SETTINGS: AppleCompatSetting[] = [
  {
    id: "pppc",
    label: "Privacy Preferences Policy Control",
    payloadType: "com.apple.TCC.configuration-profile-policy",
    platforms: ["MACOS"],
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "Privacy Preferences Policy Control payload",
    description: "Grants or denies macOS privacy services for a signed app without exposing raw profile XML.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MACOS_UPLOAD_SOURCE],
    builder: "pppc",
    fields: [
      field("identifier", "App identifier", "string", "Bundle identifier or absolute path of the target app.", "com.example.app"),
      field("identifierType", "Identifier type", "string", "Apple PPPC identifier type.", "bundleID", undefined, ["bundleID", "path"]),
      field("codeRequirement", "Code requirement", "textarea", "Designated requirement for the target app.", ""),
      field("service", "Privacy service", "string", "Service key inside the PPPC Services dictionary.", "Accessibility"),
      field("authorization", "Authorization", "string", "Permission decision for the selected service.", "Allow", undefined, [
        "Allow",
        "Deny",
        "AllowStandardUserToSetSystemService",
      ]),
    ],
  },
  {
    id: "managed-preferences",
    label: "Managed Preferences",
    payloadType: "com.apple.ManagedClient.preferences",
    platforms: ["MACOS"],
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "Custom settings / managed preferences payload",
    description: "Writes a forced managed preference domain and key using the Apple ManagedClient preferences payload.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MACOS_UPLOAD_SOURCE],
    builder: "managed-preferences",
    fields: [
      field("domain", "Preference domain", "string", "Preference domain to manage.", "com.example.app"),
      field("key", "Preference key", "string", "Preference key in the forced settings dictionary.", "ExampleKey"),
      field("value", "Preference value", "textarea", "String value written under the managed key.", "ExampleValue"),
    ],
  },
  {
    id: "associated-domains",
    label: "Associated Domains",
    payloadType: "com.apple.associated-domains",
    platforms: ["IOS", "MACOS", "TVOS", "VISIONOS"],
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "Associated Domains payload",
    description: "Assigns associated domains to an app identifier, for example web credentials or universal links.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MOBILE_DEVICE_PROFILES_SOURCE],
    builder: "associated-domains",
    fields: [
      field("applicationIdentifier", "Application identifier", "string", "Team ID plus bundle identifier.", "ABCDE12345.com.example.app"),
      field("associatedDomains", "Associated domains", "list", "One domain rule per line.", ["webcredentials:example.com"]),
    ],
  },
  {
    id: "managed-login-items",
    label: "Managed Login Items",
    payloadType: "com.apple.servicemanagement",
    platforms: ["MACOS"],
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "Managed Login Items payload",
    description: "Controls managed background services and login items on macOS.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MACOS_UPLOAD_SOURCE],
    builder: "managed-login-items",
    fields: [
      field("teamIdentifier", "Team identifier", "string", "Developer Team ID of the managed item.", "ABCDE12345"),
      field("bundleIdentifier", "Bundle identifier", "string", "Bundle identifier of the managed item.", "com.example.agent"),
      field("comment", "Comment", "string", "Administrative note stored with the rule.", "Managed by Relution policy"),
    ],
  },
  {
    id: "network-relay",
    label: "Network Relay",
    payloadType: "com.apple.relay.managed",
    platforms: ["IOS", "MACOS"],
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "Network Relay payload",
    description: "Creates a valid profile shell for Apple network relay keys that are merged from JSON.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MOBILE_DEVICE_PROFILES_SOURCE],
    builder: "generic-json",
    fields: [
      objectListField("relays", "Relays", "Relay server chain entries written to the Relays payload key.", [], "Relays", [
        objectField("http2RelayUrl", "HTTP/2 relay URL", "string", "HTTP/2 relay URL or URI template.", "", "HTTP2RelayURL"),
        objectField("http3RelayUrl", "HTTP/3 relay URL", "string", "HTTP/3 relay URL or URI template.", "", "HTTP3RelayURL"),
        objectField("payloadCertificateUuid", "Certificate payload UUID", "string", "UUID of the identity certificate payload.", "", "PayloadCertificateUUID"),
        objectField("rawPublicKeys", "Raw public keys", "list", "One DER-encoded raw public key per line.", [], "RawPublicKeys"),
        objectField(
          "additionalHttpHeaderFields",
          "Additional HTTP headers",
          "key-value-list",
          "Custom HTTP header names and values sent to the relay.",
          {},
          "AdditionalHTTPHeaderFields",
        ),
      ]),
      field("payloadKeysJson", "Payload keys JSON", "json", "JSON object merged into the Apple payload.", "{\n  \"Relays\": []\n}"),
    ],
  },
  {
    id: "certificate-transparency",
    label: "Certificate Transparency",
    payloadType: "com.apple.security.certificatetransparency",
    platforms: APPLE_COMMON_PLATFORMS,
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "Certificate Transparency payload",
    description: "Creates a valid profile shell for certificate transparency exceptions merged from JSON.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MOBILE_DEVICE_PROFILES_SOURCE],
    builder: "generic-json",
    fields: [
      field(
        "disabledForDomains",
        "Disabled domains",
        "list",
        "Domain names excluded from certificate transparency enforcement. Use a leading dot for subdomains.",
        [],
        "DisabledForDomains",
      ),
      field(
        "disabledForCertsJson",
        "Disabled certificate hashes JSON",
        "json",
        "JSON array of certificate hash dictionaries, for example Algorithm and Hash entries.",
        "[]",
        "DisabledForCerts",
      ),
      field("payloadKeysJson", "Payload keys JSON", "json", "JSON object merged into the Apple payload.", "{\n  \"DisabledForDomains\": []\n}"),
    ],
  },
  {
    id: "smart-card",
    label: "Smart Card",
    payloadType: "com.apple.security.smartcard",
    platforms: ["MACOS"],
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "Smart Card payload",
    description: "Creates a valid profile shell for macOS smart card keys merged from JSON.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MACOS_UPLOAD_SOURCE],
    builder: "generic-json",
    fields: [
      field("allowSmartCard", "Allow smart card", "boolean", "Allow smart cards for authentication operations.", true, "allowSmartCard"),
      field("userPairing", "User pairing", "boolean", "Prompt users to pair suitable unpaired cards with their account.", true, "UserPairing"),
      field("oneCardPerUser", "One card per user", "boolean", "Allow each user to pair with only one smart card.", false, "oneCardPerUser"),
      field("enforceSmartCard", "Enforce smart card", "boolean", "Require smart card authentication for login and unlock.", false, "enforceSmartCard"),
      field("payloadKeysJson", "Payload keys JSON", "json", "JSON object merged into the Apple payload.", "{\n  \"allowSmartCard\": true\n}"),
    ],
  },
  {
    id: "printing",
    label: "Printing",
    payloadType: "com.apple.mcxprinting",
    platforms: ["MACOS"],
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "Printing payload",
    description: "Creates a valid profile shell for managed printing keys merged from JSON.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MACOS_UPLOAD_SOURCE],
    builder: "generic-json",
    fields: [
      objectListField("userPrinterList", "Printers", "Managed printer entries written to UserPrinterList.", [], "UserPrinterList", [
        objectField("displayName", "Display name", "string", "Printer display name.", "", "DisplayName"),
        objectField("deviceUri", "Device URI", "string", "Printer device URI.", "", "DeviceURI"),
        objectField("location", "Location", "string", "Printer location.", "", "Location"),
        objectField("model", "Model", "string", "Printer model.", "", "Model"),
        objectField("ppdUrl", "PPD URL", "string", "PPD URL for the printer.", "", "PPDURL"),
        objectField("printerLocked", "Lock printer", "boolean", "Lock this printer entry.", false, "PrinterLocked"),
      ]),
      field("payloadKeysJson", "Payload keys JSON", "json", "JSON object merged into the Apple payload.", "{\n  \"UserPrinterList\": []\n}"),
    ],
  },
  {
    id: "network-usage-rules",
    label: "Network Usage Rules",
    payloadType: "com.apple.networkusagerules",
    platforms: ["IOS"],
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "Network Usage Rules payload",
    description: "Creates a valid profile shell for network usage rules merged from JSON.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MOBILE_DEVICE_PROFILES_SOURCE],
    builder: "generic-json",
    fields: [
      objectListField("applicationRules", "Application rules", "Rules for managed app cellular and roaming data use.", [], "ApplicationRules", [
        objectField("appIdentifierMatches", "App identifier matches", "list", "Managed app bundle identifiers or wildcard prefixes, one per line.", [], "AppIdentifierMatches"),
        objectField("allowCellularData", "Allow cellular data", "boolean", "Allow matching managed apps to use cellular data.", true, "AllowCellularData"),
        objectField(
          "allowRoamingCellularData",
          "Allow roaming cellular data",
          "boolean",
          "Allow matching managed apps to use cellular data while roaming.",
          true,
          "AllowRoamingCellularData",
        ),
      ]),
      field("payloadKeysJson", "Payload keys JSON", "json", "JSON object merged into the Apple payload.", "{\n  \"ApplicationRules\": []\n}"),
    ],
  },
  {
    id: "system-migration",
    label: "System Migration",
    payloadType: "com.apple.systemmigration",
    platforms: ["MACOS"],
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "System Migration payload",
    description: "Creates a valid profile shell for macOS migration behavior keys merged from JSON.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MACOS_UPLOAD_SOURCE],
    builder: "generic-json",
    fields: [
      field("migrationContext", "Migration context", "string", "Context value for the custom migration behavior.", "Windows"),
      field("sourcePath", "Source path", "string", "Path to the source on the migrated system.", ""),
      field("sourcePathInUserHome", "Source in user home", "boolean", "Treat the source path as relative to the user's home folder.", false),
      field("targetPath", "Target path", "string", "Path to the destination on the Mac.", ""),
      field("targetPathInUserHome", "Target in user home", "boolean", "Treat the target path as relative to the user's home folder.", false),
      field(
        "payloadKeysJson",
        "Payload keys JSON",
        "json",
        "JSON object merged into the Apple payload.",
        "{\n  \"CustomBehavior\": [\n    {\n      \"Context\": \"Windows\",\n      \"Paths\": []\n    }\n  ]\n}",
      ),
    ],
  },
  {
    id: "acme-certificate",
    label: "ACME Certificate",
    payloadType: "com.apple.security.acme",
    platforms: APPLE_COMMON_PLATFORMS,
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "ACME Certificate payload",
    description: "Requests a client certificate from an Automated Certificate Management Environment server.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MOBILE_DEVICE_PROFILES_SOURCE, JAMF_MACOS_UPLOAD_SOURCE],
    builder: "generic-json",
    fields: [
      field("clientIdentifier", "Client identifier", "string", "Unique ACME client identifier used as the permanent identifier.", "", "ClientIdentifier"),
      field("directoryUrl", "Directory URL", "string", "HTTPS ACME directory URL.", "https://acme.example.test/directory", "DirectoryURL"),
      field("hardwareBound", "Hardware bound key", "boolean", "Bind the private key to the device hardware.", false, "HardwareBound"),
      field("keyType", "Key type", "string", "Type of key pair to generate.", "RSA", "KeyType", ["RSA", "ECSECPrimeRandom"]),
      field("keySize", "Key size", "integer", "Key size for the generated key pair.", 2048, "KeySize"),
      field("subjectJson", "Subject JSON", "json", "Apple subject array requested for the certificate.", "[\n  [[\"CN\", \"example\"]]\n]", "Subject"),
      field("subjectAltNameJson", "Subject alternative name JSON", "json", "SubjectAltName dictionary, for example dNSName or rfc822Name.", "{}", "SubjectAltName"),
      field("extendedKeyUsage", "Extended key usage OIDs", "list", "Extended key usage OIDs, one per line.", [], "ExtendedKeyUsage"),
      field("usageFlags", "Usage flags", "integer", "Key usage bit field requested for the certificate.", 5, "UsageFlags"),
      field("attest", "Attest", "boolean", "Request ACME device attestation when supported.", false, "Attest"),
      field("allowAllAppsAccess", "Allow all apps access", "boolean", "Allow all apps to access the private key.", false, "AllowAllAppsAccess"),
      field("keyIsExtractable", "Key is extractable", "boolean", "Mark the keychain identity according to Apple's KeyIsExtractable payload key.", true, "KeyIsExtractable"),
      field(
        "payloadKeysJson",
        "Payload keys JSON",
        "json",
        "JSON object merged into the Apple payload.",
        "{\n  \"ClientIdentifier\": \"\",\n  \"DirectoryURL\": \"https://acme.example.test/directory\",\n  \"HardwareBound\": false,\n  \"KeyType\": \"RSA\",\n  \"KeySize\": 2048,\n  \"Subject\": [[[\"CN\", \"example\"]]]\n}",
      ),
    ],
  },
  {
    id: "autonomous-single-app-mode",
    label: "Autonomous Single App Mode",
    payloadType: "com.apple.asam",
    platforms: ["MACOS"],
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "Autonomous Single App Mode payload",
    description: "Grants specified macOS apps access to Autonomous Single App Mode.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MACOS_UPLOAD_SOURCE],
    builder: "generic-json",
    fields: [
      objectListField("allowedApplications", "Allowed applications", "Applications allowed to use Autonomous Single App Mode.", [], "AllowedApplications", [
        objectField("bundleIdentifier", "Bundle identifier", "string", "Unique app bundle identifier.", "", "BundleIdentifier"),
        objectField("teamIdentifier", "Team identifier", "string", "Developer Team ID used when the app was signed.", "", "TeamIdentifier"),
      ]),
      field("payloadKeysJson", "Payload keys JSON", "json", "JSON object merged into the Apple payload.", "{\n  \"AllowedApplications\": []\n}"),
    ],
  },
  {
    id: "cellular-private-network",
    label: "Cellular Private Network",
    payloadType: "com.apple.cellularprivatenetwork.managed",
    platforms: ["IOS"],
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "Cellular Private Network payload",
    description: "Provides private cellular network deployment metadata, preference over Wi-Fi, and optional geofences.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MOBILE_DEVICE_PROFILES_SOURCE],
    builder: "generic-json",
    fields: [
      field("dataSetName", "Dataset name", "string", "Name of the private network configuration dataset.", "", "DataSetName"),
      field("versionNumber", "Version number", "string", "Dataset version number used by the system to track updates.", "1", "VersionNumber"),
      field("networkIdentifier", "Network identifier", "string", "3GPP Coordinated NID string used to match a SIM.", "", "NetworkIdentifier"),
      field("csgNetworkIdentifier", "CSG network identifier", "string", "3GPP CSG_ID string used to match a SIM.", "", "CsgNetworkIdentifier"),
      field("cellularDataPreferred", "Prefer cellular data", "boolean", "Prefer this private network over Wi-Fi.", false, "CellularDataPreferred"),
      field("enableNrStandalone", "Enable NR standalone", "boolean", "Mark this private network as NR Standalone.", false, "EnableNRStandalone"),
      objectListField("geofences", "Geofences", "Geofence entries for private network coverage areas.", [], "Geofences", [
        objectField("geofenceId", "Geofence ID", "string", "Identifier unique inside the geofence list.", "", "GeofenceId"),
        objectField("latitude", "Latitude", "number", "Latitude of the geofence.", 0, "Latitude"),
        objectField("longitude", "Longitude", "number", "Longitude of the geofence.", 0, "Longitude"),
        objectField("radius", "Radius", "number", "Radius of the geofence in meters.", 0, "Radius"),
      ]),
      field(
        "payloadKeysJson",
        "Payload keys JSON",
        "json",
        "JSON object merged into the Apple payload.",
        "{\n  \"DataSetName\": \"\",\n  \"VersionNumber\": \"1\"\n}",
      ),
    ],
  },
  {
    id: "certificate-preference",
    label: "Certificate Preference",
    payloadType: "com.apple.security.certificatepreference",
    platforms: ["MACOS"],
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "Certificate Preference payload",
    description: "Creates a certificate preference item in the user's keychain referencing a certificate payload in the same profile.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MACOS_UPLOAD_SOURCE],
    builder: "generic-json",
    fields: [
      field("name", "Name", "string", "Email address or other name for which a preferred certificate is requested.", "", "Name"),
      field("payloadCertificateUuid", "Certificate payload UUID", "string", "UUID of the certificate payload within the same profile.", "", "PayloadCertificateUUID"),
      field(
        "payloadKeysJson",
        "Payload keys JSON",
        "json",
        "JSON object merged into the Apple payload.",
        "{\n  \"Name\": \"\",\n  \"PayloadCertificateUUID\": \"\"\n}",
      ),
    ],
  },
  {
    id: "certificate-revocation",
    label: "Certificate Revocation",
    payloadType: "com.apple.security.certificaterevocation",
    platforms: ["IOS", "VISIONOS"],
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "Certificate Revocation payload",
    description: "Configures certificate revocation checking for specified certificate public key hashes.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MOBILE_DEVICE_PROFILES_SOURCE],
    builder: "generic-json",
    fields: [
      field(
        "enabledForCertsJson",
        "Enabled certificate hashes JSON",
        "json",
        "JSON array for Apple's EnabledForCerts payload key.",
        "[]",
        "EnabledForCerts",
      ),
      field("payloadKeysJson", "Payload keys JSON", "json", "JSON object merged into the Apple payload.", "{\n  \"EnabledForCerts\": []\n}"),
    ],
  },
  {
    id: "exchange-web-services",
    label: "Exchange Web Services",
    payloadType: "com.apple.ews.account",
    platforms: ["MACOS"],
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "Exchange Web Services payload",
    description: "Configures an Exchange Web Services account for macOS.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MACOS_UPLOAD_SOURCE],
    builder: "generic-json",
    fields: [
      field("emailAddress", "Email address", "string", "Full email address for the account.", "", "EmailAddress"),
      field("userName", "User name", "string", "User name for noninteractive installation through MDM.", "", "UserName"),
      field("host", "Host", "string", "Exchange server host name or IP address.", "", "Host"),
      field("ssl", "SSL", "boolean", "Enable SSL for the primary connection.", true, "SSL"),
      field("port", "Port", "integer", "Primary server port number.", 443, "Port"),
      field("path", "Path", "string", "Primary server path.", "", "Path"),
      field("oauth", "OAuth", "boolean", "Enable OAuth authentication.", false, "OAuth"),
      field("oauthSignInUrl", "OAuth sign-in URL", "string", "URL for web view OAuth authentication when autodiscovery is not used.", "", "OAuthSignInURL"),
      field("password", "Password", "string", "Account password. Apple recommends using this only with encrypted profiles.", "", "Password"),
      field("payloadCertificateUuid", "Certificate payload UUID", "string", "UUID of the identity certificate payload in the same profile.", "", "PayloadCertificateUUID"),
      field("authenticationCertificateUuid", "Authentication certificate UUID", "string", "Legacy UUID of the certificate payload for the identity credential.", "", "AuthenticationCertificateUUID"),
      field("allowMailDrop", "Allow Mail Drop", "boolean", "Enable Mail Drop for the account.", false, "allowMailDrop"),
      field("externalHost", "External host", "string", "External server address.", "", "ExternalHost"),
      field("externalSsl", "External SSL", "boolean", "Enable SSL for the external server.", true, "ExternalSSL"),
      field("externalPort", "External port", "integer", "External server port number.", 443, "ExternalPort"),
      field("externalPath", "External path", "string", "External server path.", "", "ExternalPath"),
      field("payloadKeysJson", "Payload keys JSON", "json", "JSON object merged into the Apple payload.", "{\n  \"SSL\": true,\n  \"ExternalSSL\": true\n}"),
    ],
  },
  {
    id: "identity-preference",
    label: "Identity Preference",
    payloadType: "com.apple.security.identitypreference",
    platforms: ["MACOS"],
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "Identity Preference payload",
    description: "Configures the user's preferred identity for an email address or other name.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MACOS_UPLOAD_SOURCE],
    builder: "generic-json",
    fields: [
      field("name", "Name", "string", "Email address or other name for which an identity is requested.", "", "Name"),
      field("payloadCertificateUuid", "Certificate payload UUID", "string", "UUID of the certificate payload within the same profile.", "", "PayloadCertificateUUID"),
      field(
        "payloadKeysJson",
        "Payload keys JSON",
        "json",
        "JSON object merged into the Apple payload.",
        "{\n  \"Name\": \"\",\n  \"PayloadCertificateUUID\": \"\"\n}",
      ),
    ],
  },
  {
    id: "lights-out-management",
    label: "Lights Out Management",
    payloadType: "com.apple.lom",
    platforms: ["MACOS"],
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "Lights Out Management payload",
    description: "Configures macOS lights-out management controller and device certificate references.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MACOS_UPLOAD_SOURCE],
    builder: "generic-json",
    fields: [
      field("controllerCaCertificateUuids", "Controller CA certificate UUIDs", "list", "Controller CA certificate payload UUIDs.", [], "ControllerCACertificateUUIDs"),
      field("controllerCertificateUuid", "Controller certificate UUID", "string", "Controller certificate payload UUID.", "", "ControllerCertificateUUID"),
      field("deviceCaCertificateUuids", "Device CA certificate UUIDs", "list", "Device CA certificate payload UUIDs.", [], "DeviceCACertificateUUIDs"),
      field("deviceCertificateUuid", "Device certificate UUID", "string", "Device certificate payload UUID.", "", "DeviceCertificateUUID"),
      field("payloadKeysJson", "Payload keys JSON", "json", "JSON object merged into the Apple payload.", "{}"),
    ],
  },
  {
    id: "lock-screen-message",
    label: "Lock Screen Message",
    payloadType: "com.apple.shareddeviceconfiguration",
    platforms: ["IOS"],
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "Lock Screen Message payload",
    description: "Configures asset tag, lost-device return message, and lock screen footnote text.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MOBILE_DEVICE_PROFILES_SOURCE],
    builder: "generic-json",
    fields: [
      field("assetTagInformation", "Asset tag information", "string", "Asset tag information displayed on the lock screen.", "", "AssetTagInformation"),
      field("ifLostReturnToMessage", "If-lost return message", "textarea", "Message shown to help return a lost device.", "", "IfLostReturnToMessage"),
      field("lockScreenFootnote", "Lock screen footnote", "textarea", "Footnote shown on the lock screen.", "", "LockScreenFootnote"),
      field("payloadKeysJson", "Payload keys JSON", "json", "JSON object merged into the Apple payload.", "{}"),
    ],
  },
  {
    id: "tv-remote",
    label: "TV Remote",
    payloadType: "com.apple.tvremote",
    platforms: ["IOS", "TVOS"],
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "TV Remote payload",
    description: "Restricts which iOS devices and Apple TVs may pair for Apple TV Remote control.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MOBILE_DEVICE_PROFILES_SOURCE],
    builder: "generic-json",
    fields: [
      objectListField("allowedRemotes", "Allowed remotes", "Permitted iOS remote devices by MAC address.", [], "AllowedRemotes", [
        objectField("remoteDeviceId", "Remote device ID", "string", "MAC address of a permitted iOS remote device.", "", "RemoteDeviceID"),
      ]),
      objectListField("allowedTvs", "Allowed TVs", "Permitted Apple TV devices by MAC address.", [], "AllowedTVs", [
        objectField("tvDeviceId", "TV device ID", "string", "MAC address of a permitted Apple TV.", "", "TVDeviceID"),
        objectField("tvDeviceName", "TV device name", "string", "Name of a permitted Apple TV.", "", "TVDeviceName"),
      ]),
      field("payloadKeysJson", "Payload keys JSON", "json", "JSON object merged into the Apple payload.", "{\n  \"AllowedRemotes\": [],\n  \"AllowedTVs\": []\n}"),
    ],
  },
  {
    id: "xsan",
    label: "Xsan",
    payloadType: "com.apple.xsan",
    platforms: ["MACOS"],
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "Xsan payload",
    description: "Configures an Xsan client system.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MACOS_UPLOAD_SOURCE],
    builder: "generic-json",
    fields: [
      field("sanName", "SAN name", "string", "SAN name exactly as defined on the metadata server.", "", "sanName"),
      field("sharedSecret", "Shared secret", "string", "Shared secret used for Xsan network authentication.", "", "sharedSecret"),
      field("sanAuthMethod", "SAN authentication method", "string", "Authentication method for the SAN.", "auth_secret", "sanAuthMethod", ["auth_secret"]),
      field("sanConfigUrls", "SAN config URLs", "list", "LDAP URLs where Xsan systems obtain SAN configuration updates.", [], "sanConfigURLs"),
      field("fsNameServers", "File system name servers", "list", "SAN File System Name Server coordinators.", [], "fsnameservers"),
      field(
        "payloadKeysJson",
        "Payload keys JSON",
        "json",
        "JSON object merged into the Apple payload.",
        "{\n  \"sanName\": \"\",\n  \"sharedSecret\": \"\",\n  \"sanAuthMethod\": \"auth_secret\"\n}",
      ),
    ],
  },
  {
    id: "xsan-preferences",
    label: "Xsan Preferences",
    payloadType: "com.apple.xsan.preferences",
    platforms: ["MACOS"],
    status: "mobileconfig-backed",
    relutionTransportType: "APPLE_MOBILECONFIG",
    jamfFeature: "Xsan Preferences payload",
    description: "Configures Xsan volume auto-mount and Distributed LAN Client preferences.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MACOS_UPLOAD_SOURCE],
    builder: "generic-json",
    fields: [
      field("onlyMount", "Only mount", "list", "SAN volumes to automatically mount at startup.", [], "onlyMount"),
      field("denyMount", "Deny mount", "list", "SAN volumes excluded from automatic mounting.", [], "denyMount"),
      field("useDlc", "Use DLC", "boolean", "Use Distributed LAN Client for all volumes.", false, "useDLC"),
      field("preferDlc", "Prefer DLC", "list", "StorNext volumes that should prefer DLC.", [], "preferDLC"),
      field("denyDlc", "Deny DLC", "list", "StorNext volumes that must not use DLC.", [], "denyDLC"),
      field("payloadKeysJson", "Payload keys JSON", "json", "JSON object merged into the Apple payload.", "{}"),
    ],
  },
  {
    id: "declarative-management-declarations",
    label: "Declarative Management Declarations",
    payloadType: "declarative-management",
    platforms: APPLE_COMMON_PLATFORMS,
    status: "not-mobileconfig-wireable",
    jamfFeature: "Declarative Device Management declarations",
    description: "DDM declarations are not standard .mobileconfig payloads, so this editor reports the gap without creating a Relution APPLE_MOBILECONFIG entry.",
    sourceUrls: [APPLE_PROFILE_SOURCE, JAMF_MOBILE_DEVICE_PROFILES_SOURCE],
    builder: "generic-json",
    fields: [],
  },
];

function field(
  id: string,
  label: string,
  kind: AppleCompatFieldKind,
  description: string,
  defaultValue: unknown,
  payloadKey?: string,
  options?: string[],
): AppleCompatField {
  return buildField({ id, label, kind, description, defaultValue }, { payloadKey, options });
}

function objectListField(
  id: string,
  label: string,
  description: string,
  defaultValue: unknown,
  payloadKey: string,
  itemFields: AppleCompatObjectField[],
): AppleCompatField {
  return { id, label, kind: "object-list", description, defaultValue, payloadKey, itemFields };
}

function objectField(
  id: string,
  label: string,
  kind: AppleCompatScalarFieldKind,
  description: string,
  defaultValue: unknown,
  payloadKey?: string,
  options?: string[],
): AppleCompatObjectField {
  return buildField({ id, label, kind, description, defaultValue }, { payloadKey, options });
}

function buildField<T extends AppleCompatField | AppleCompatObjectField>(
  base: T,
  optionals: { readonly payloadKey?: string | undefined; readonly options?: string[] | undefined },
): T {
  return {
    ...base,
    ...(optionals.payloadKey === undefined ? {} : { payloadKey: optionals.payloadKey }),
    ...(optionals.options === undefined ? {} : { options: optionals.options }),
  };
}
