/** Adds compatible configuration records to persisted policies. */
import { appleCompatSettingsForPlatform, createAppleCompatConfiguration, findAppleCompatSetting } from "./apple-compat.js";
import { appleSchemaEntriesForPlatform, createAppleSchemaProfileConfiguration, findAppleSchemaEntry, type AppleSchemaCatalog } from "./apple-schema.js";
import { findTemplate, type RelutionTemplateBundle } from "./templates.js";
import { stringValue, type JsonRecord } from "./utils/json-guards.js";
import { incompatibleWorkspaceConfigurationMessage, invalidWorkspacePolicyPlatformMessage, workspaceConfigurationType } from "./workspace-model.js";
import { configurationTarget } from "./workspace-configuration-target.js";
import { createConfiguration } from "./workspace-configuration-builder.js";
import { loadWorkspace, saveWorkspace, WorkspaceInputError, type AddAppleCompatConfigurationOptions, type AddAppleSchemaProfileOptions, type AddConfigurationOptions, type PolicyWorkspace } from "./workspace.js";

export function addConfigurationToWorkspace(path: string, bundle: RelutionTemplateBundle, options: AddConfigurationOptions): PolicyWorkspace { return addConfiguration(path, options, ({ configurations }) => { const template = findTemplate(bundle, options.type); if (template === undefined) throw new WorkspaceInputError(`Unknown configuration type: ${options.type}`); if (!template.multiConfig && configurations.some((entry) => workspaceConfigurationType(entry) === options.type)) throw new WorkspaceInputError(`Configuration type ${options.type} is not multi-config and already exists in this policy version`); return createConfiguration(template, bundle); }); }
export function addAppleCompatConfigurationToWorkspace(path: string, options: AddAppleCompatConfigurationOptions): PolicyWorkspace { return addConfiguration(path, options, ({ policy }) => { const platform = policyPlatform(policy.document); const setting = findAppleCompatSetting(options.settingId); if (setting === undefined || !appleCompatSettingsForPlatform(platform).some((candidate) => candidate.id === setting.id)) throw new WorkspaceInputError(incompatibleWorkspaceConfigurationMessage(`Apple compatibility setting ${options.settingId}`, platform)); return createAppleCompatConfiguration(setting.id); }); }
export function addAppleSchemaProfileToWorkspace(path: string, catalog: AppleSchemaCatalog, options: AddAppleSchemaProfileOptions): PolicyWorkspace { return addConfiguration(path, options, ({ policy }) => { const platform = policyPlatform(policy.document); const entry = findAppleSchemaEntry(catalog, options.schemaId); if (entry === undefined || entry.kind !== "profile") throw new WorkspaceInputError(`Apple profile schema not found: ${options.schemaId}`); if (!appleSchemaEntriesForPlatform(catalog, platform, "profile").some((candidate) => candidate.id === entry.id)) throw new WorkspaceInputError(incompatibleWorkspaceConfigurationMessage(`Apple profile schema ${options.schemaId}`, platform)); return createAppleSchemaProfileConfiguration(entry); }); }
function addConfiguration(path: string, options: { policyPath: string; versionIndex: number }, create: (target: ReturnType<typeof configurationTarget>) => JsonRecord): PolicyWorkspace { const workspace = loadWorkspace(path); const target = configurationTarget(workspace, options); target.configurations.push(create(target)); saveWorkspace(path, workspace); return workspace; }
function policyPlatform(document: JsonRecord): string { const platform = stringValue(document.platform); if (platform === undefined) throw new WorkspaceInputError(invalidWorkspacePolicyPlatformMessage(document.platform)); return platform; }
